Part1 양진수 week3
codeit-bootcamp-frontend/1-Weekly-Mission pull request #101
Opened 2023-09-23 15:20 UTC by Accept77

## 요구사항

### 기본

- [x]  [기본] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용했나요?
- [x]  [랜딩 페이지] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 Linkbrary 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정했나요?
- [x]  [랜딩 페이지] 미리보기에서 제목은 “Linkbrary”, 설명은 “세상의 모든 정보를 쉽게 저장하고 관리해 보세요”로 설정했나요?
- [x]  [랜딩 페이지] 주소와 이미지는 자유롭게 설정했나요?
- [x]  [랜딩 페이지] Tablet 사이즈에서 화면의 너비가 1199px 이하로 작아질 때 “Linkbrary” 로고와 “로그인” 버튼 사이의 간격은 유지하고 좌우 여백이 줄어드나요?
- [x]  [랜딩 페이지] 최소 좌우 여백은 “Linkbrary” 로고의 왼쪽에 여백 32px, “로그인” 버튼 오른쪽 여백 32px을 유지할 수 있도록 “Linkbrary” 로고와 “로그인" 버튼의 간격이 가까워지나요?
- [x]  [랜딩 페이지] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용했나요?
- [x]  [랜딩 페이지] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차나요?
(이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [x]  [랜딩 페이지] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 간격이 커지나요?
- [x]  [로그인, 회원가입 페이지] Tablet 사이즈에서 디자인은 PC사이즈와 동일한가요?
- [x]  [로그인, 회원가입 페이지] Mobile 사이즈에서 좌우 여백 32px 제외하고 내부 요소들이 너비를 모두 차지하나요?
- [x]  [로그인, 회원가입 페이지] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않나요?

### 심화

- [x]  [심화] 팀원의 위클리 미션 PR에 코드 리뷰를 남겼나요?
- [ ]  [심화] 랜딩 페이지 Mobile 사이즈에서 제품 소개 영역의 순서를 제목, 설명, 이미지 => 제목, 이미지, 설명 순서로 변경했나요?

## 주요 변경사항

- 오탈자 수정
- 시멘틱 태그 다시 수정
- kebab-case로 변경

## 스크린샷

![image](https://cdn.discordapp.com/attachments/1152155333926592513/1155161394317099058/image.png)

## 멘토에게

- 심화에서 영역의 순서의 변경하는 것에서 order 속성을 사용하는 게 아니라 html 코드부터 다시 짜야 한다고 생각했는데 이 의견 말고 다른 방법이 있는지 궁금합니다.
- 이미지 크기가 조정을 최대한 능력 안에서 구현했습니다.
- 미리보기 페이지는 다 디버거로 확인해봤습니다. 혹시 몰라서 링크 남깁니다.
- 처음부터 레이아웃을 짤 때부터 반응형으로 생각했다면 더 좋은 코드가 나왔을 것이라고 생각합니다.
- https://chipper-puppy-1e2af4.netlify.app/
- 항상감사합니다 :D

2023-09-25 04:31 UTC, addiescode-sj commented
## 머지 전 체크

<img width="640" alt="image" src="https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/69444278/e491122b-e91e-471d-834c-f60831cfab67">

### 모바일 이미지 사이즈

(max-width: 767px) 의 브레이크포인트가 적용된 경우
img-box의 사이즈가 고정적으로 아래와 같이 구현되도록 해주셨는데요,

```
@media (max-width: 767px)
.img-box {
    width: 330px;
    height: 290px;

```

요구사항을 보면 고정적인 width와 height를 가지는게 아닌, 
페이지 좌우 여백을 제외한 width 100%로 채우면서 height도 비율에 맞게 조절되는것이 맞아보이네요.

즉 width:100%로, height의 경우엔 기본값인 auto로 적용되면 될 것 같습니다 (기본값은 스타일에 명시하지않으셔도됩니다).


### 1199px 이하로 작아질 때 요구사항대로 레이아웃 유지

- [랜딩 페이지] Tablet 사이즈에서 화면의 너비가 1199px 이하로 작아질 때 “Linkbrary” 로고와 “로그인” 버튼 사이의 간격은 유지하고 좌우 여백이 줄어드나요?

이 1199px이하로 작아지게되면 두개 요소 사이의 간격이 유지되며 좌우 여백이 줄어들어야하는데 이 점 반영이 안되어있네요 :)
한번 체크해주세요~

2023-09-25 04:33 UTC, addiescode-sj commented
## 멘토의 답변 

### 심화에서 영역의 순서의 변경하는 것에서 order 속성을 사용하는 게 아니라 html 코드부터 다시 짜야 한다고 생각했는데 이 의견 말고 다른 방법이 있는지 궁금합니다.

html의 경우 간단하게 조건부 렌더링을 할 수 있는 방법이 따로 없고, 
기본적으로 문서안에 있는 모든 엘리먼트를 파싱하기때문에 반응형 레이아웃에 맞춰 html 엘리먼트를 바꾸거나 구조를 짜는것은 무의미합니다 :) 지금처럼 flexbox의 order속성을 사용해주시는게 제일 베스트일것 같아요!

2023-09-25 05:05 UTC, addiescode-sj requested changes
진수님~! 이번주도 수고하셨습니다. 항상 너무 깔끔하게 잘 코드를 정리하시네요 :)
읽기 수월한것 같아요. 다만 이번주 코드는 미션사항을 제대로 반영하지못한것 몇개가 보여서, request change드리고 수요일까지 수정할수있게끔 시간 더 드리겠습니다 :) 코멘트들 체크해보세요!
그리고 PR걸때 병합 대상을 main브랜치로 잘못 잡으신것같아요. part1-양진수 base 브랜치를 바라볼수있게끔 수정도 부탁드릴게요 :)

2023-09-25 05:05 UTC, addiescode-sj commented on style.css
> +    width: 120%;
아하 왜 이미지를 이런식으로 %를 바꿔주면서 주었나했더니,
이제보니 background에 이미지를 위치시키려고 그러셨군요 :)
이런건 변경할 일이 많지 않으니 굳이 코드로 만들어줄 필요 없어요. 디자이너가 준 이미지 그대로 export 하시면 됩니다 :) 

figma에서 이렇게 export하고 이미지 그대로 넣어보실래요?

<img width="238" alt="image" src="https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/69444278/8a7b4cef-76fc-4768-8eab-a51b0afb4433">

2023-09-26 04:15 UTC, Accept77 commented on .github/delete-merged-branch-config.yml
> +name: delete branch on close pr
그냥 .github의 디렉토리를 무시하는 처리를 했는데 다른 파일 하나는 PR할때 양식인거같은데 둘다 처리를 했습니다
확인부탁드립니다!

2023-09-26 04:16 UTC, Accept77 commented on index.html
> +    <link rel="stylesheet" href="reset.css">
@import 문법을 사용하면 css 로딩속도가 느려져서 일부로 링크의 방법으로 했습니다! 나중에 멘토링시간에 추가로 질문하겠습니다!

2023-09-27 05:00 UTC, addiescode-sj approved these changes
진수님 수고하셨어요!
.gitignore에 주의사항 하나 코멘트 드렸어요.
참고해보시고, 다음 위클리미션때부터 적용해주셔도 무방할 것 같습니다.

Approve 드리겠습니다! 👍

2023-09-27 05:00 UTC, addiescode-sj commented on index.html
> +    <link rel="stylesheet" href="reset.css">
네, 편한 방법대로 참고하셔서 정해주세요 :)

2023-09-27 09:58 UTC, merged