[박세은] week3
codeit-bootcamp-frontend/1-Weekly-Mission pull request #103
Opened 2023-09-23 18:06 UTC by marchfirst01

## 요구사항

### 기본

## 주요 변경사항

-
-

## 스크린샷

![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/140829640/a21fa4c4-11dd-4082-9943-44cdf9a08f72)

## 멘토에게

- 죄송합니다, 이번 주에 개인적으로 바쁜 일정들이 많아서 완성하지 못했습니다.,,,
- 조금이지만 구현하면서 궁금한 점은, 최소 패딩 32px을 유지하면서 로고와 로그인 버튼 사이의 간격을 고정시키는 방법이 이 방식으로 하는 것이 맞는지 궁금합니다.
- width를 864px로 고정하면서 margin 0 auto를 이용해 가운데 정렬하는 방식을 사용해봤는데, 그랬더니 가장자리가 흰 색으로 나타나서... 어떻게 해결해야 할지 고민입니다. body의 background-color를 header의 색으로 바꿔주자니, 다른 부분에서도 문제가 있어서.. 이 부분 궁금합니다!
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-09-25 05:44 UTC, addiescode-sj commented
## 머지 전 필수 체크 

<img width="1905" alt="image" src="https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/69444278/5fb69da2-bc77-4607-8cd5-193b045401d2">

- 지금 브라우저에서 inspect해보면 header의 전체 width를 고정값을 주고, 중앙정렬을 위해 margin: 0 auto를 써줬기때문에 양옆에 흰색 여백이 생기는 걸 볼 수 있어요.

  - 1199px이하로 작아지게 될 경우 “Linkbrary” 로고와 “로그인” 버튼 사이의 간격은 변하지 않게 고정값으로 유지하되 좌우 여백은 줄어드는게 가능
  - 1200px이상인 경우 최소 좌우 여백 32px씩 유지하면서 두 개 사이 간격이 가까워지도록 함

이렇게 두개의 브레이크포인트에서 1199px 이하에 쓰여진 디자인 요구사항대로 대처하려면, 전체 width에 고정값을 주는게 아니라 **“Linkbrary” 로고와 “로그인” 버튼 사이의 간격**에 고정값을 주는게 낫겠죠? Linkbrary” 로고의 margin-right로 줘도 되고, flexbox를 이용하고있으니 gap속성을 이용해도 될 것 같아요 :)

- 전체적으로 반응형 시나리오에 해당하는 화면 구현을 미완성하셨네요. 수요일 전까지 보완할 시간 드리겠습니다 :) flexbox 아이템 내의 순서를 조정하고 싶으시면 order라는 속성 이용해보세요! :) [참고](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Ordering_flex_items)

2023-09-25 05:56 UTC, addiescode-sj requested changes
세은님, 이번주도 수고하셨어요! 점점 코드 퀄리티가 좋아지고 있는데 완성을 못봐서 조금 아쉽네요..! ㅎㅎ

미완성으로 제출하셨지만, 제출하신 부분에 대한 코드리뷰는 끝냈습니다.
수요일까지 수정 및 보완할 시간 더 드려볼게요 :)

2023-09-25 05:56 UTC, addiescode-sj commented on index.html
> +
indent tab space때문에 이런 공백을 넣어주지않아도 충분히 잘 읽을 수 있어요.
불필요한 공백은 제거해주세요 :)

2023-09-25 05:56 UTC, addiescode-sj commented on signin.html
> +      <header class="header">
div의 무분별한 사용 -> 적절한 semantic elements 활용으로 바꾸셨네요. 아주 좋은 습관입니다! 👍

2023-09-25 05:56 UTC, addiescode-sj commented on style/common.css
> +@import './color.css';
오호, color변수들만 따로 추출한 css파일을 따로 만드셨군요 :)
너무 좋은 시도이지만 지금은 프로젝트 규모가 작아서 이렇게 파일을 따로 관리할 필요는 없을 것 같아요.
common.css에 컬러코드가 있는것만으로도 충분할것같습니다 :)

2023-09-25 05:56 UTC, addiescode-sj commented on style/index.css
> +  padding: 1.25rem 12.5rem;
default font-size를 16px그대로 두고 rem변환하셨네요!
이렇게 하면 매번 *16을 곱해서 계산해야하니까, 편의를 위해 rem단위의 기준이 되는 default font size를 10px로 바꿔보는 건 어때요? html 선택자 안에서 font-size 속성을 바꿔주시면 됩니다 :)

2023-09-25 05:56 UTC, addiescode-sj commented on style/index.css
> +@media (max-width: 1199px) {
이렇게 1199px max-width를 설정해주게되면 이것보다 작은 브레이크포인트와 스타일 겹침이 발생할수도있어요.
디자인을 보니 모바일 브레이크포인트도 있던데, 보다 작은 사이즈의 미디어쿼리 영역과 스타일이 겹치는 이슈를 방지하기위해 그 기준점이 되는 min-width도 같이 써주세요 :)

2023-09-26 05:22 UTC, marchfirst01 commented on style/index.css
> +  padding: 1.25rem 12.5rem;
오, 안 그래도 고민이었는데 조언 감사합니다!

2023-09-27 09:59 UTC, merged