[신혜윤] refactor/Week3
codeit-bootcamp-frontend/1-Weekly-Mission pull request #127
Opened 2023-09-26 02:59 UTC by hyeyoonS

### 기본
- [x] [기본] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용했나요?

- [x]  [랜딩 페이지] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 Linkbrary 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정했나요?

- [x]  [랜딩 페이지] 미리보기에서 제목은 “Linkbrary”, 설명은 “세상의 모든 정보를 쉽게 저장하고 관리해 보세요”로 설정했나요?

- [x]  [랜딩 페이지] 주소와 이미지는 자유롭게 설정했나요?

- [x]  [랜딩 페이지] Tablet 사이즈에서 화면의 너비가 1199px 이하로 작아질 때 “Linkbrary” 로고와 “로그인” 버튼 사이의 간격은 변하지 않게 고정값으로 유지하되 좌우 여백이 줄어드나요?

- [ ]  [랜딩 페이지] Tablet 사이즈에서 최소 좌우 여백은 “Linkbrary” 로고의 왼쪽에 여백 32px, “로그인” 버튼 오른쪽 여백 32px을 유지하고“Linkbrary” 로고와 “로그인" 버튼의 간격이 가까워지나요?

- [x]  [랜딩 페이지] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용했나요?

- [ ]  [랜딩 페이지] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차나요? (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)

- [x]  [랜딩 페이지] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 간격이 커지나요?

- [x]  [로그인, 회원가입 페이지] Tablet 사이즈에서 디자인은 PC사이즈와 동일한가요?

- [ ]  [로그인, 회원가입 페이지] Mobile 사이즈에서 좌우 여백 32px 제외하고 내부 요소들이 너비를 모두 차지하나요?

- [ ]  [로그인, 회원가입 페이지] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않나요?

### 심화
- [ ]  랜딩 페이지, 제품 소개 영역의 mobile 사이즈에서만 제목, 이미지, 설명 순서대로 배치해 주세요.

- [ ]  팀원의 위클리 미션 PR에 코드 리뷰를 남겨 주세요.

### 스크린샷
![127 0 0 1_5500_index html (1)](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/144667455/64564bf6-83f1-45b2-bb8d-9fe2d63048bc)

![127 0 0 1_5500_index html](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/144667455/2eff3946-6ed5-4d90-b575-a793b20a3d06)

### 멘토에게

1.
.main-text 에서 줄바꿈이 되는 부분은 어떻게 해야 할 지 이해를 잘 못해서 아직 구현하지 못했는데요ㅜㅜ 다음 주차 때 같이 해보겠습니다,,

2
메타태그를 적용했는데 적용이 안되는 것 같아요
이부분 성현멘토님께서 url로 바꾸면 될 것 같다고 하셨는데요, 찾아봐도 잘 모르겠어서 한 번 더 질문드립니다ㅠㅠ
이미지 url을 어떻게 가져오는건가요... ?? 저는 이미지를 저장해서 images폴더 안에 IMG_7248.jpg 이름으로 넣어두었는데 이 방법이 아닌걸까효...?? 이미지로 첨부하겠습니다,,! 

4. 
회원가입과 로그인페이지의 요소들이, 화면을 작게하여도 좁아지지 않고 옆으로 잘립니다 ㅜㅜ 
32px의 여백도 유지되지 않는데요 이것두 어디가 잘못된건지 잘 모르겠어서 이미지로 첨부하겠습니다.. ㅠㅡㅠ 

5.
회원가입과 로그인페이지의 규격을 작게 하였을 때
body크기는 작아지는 반면에 form크기는 400px 그대로 유지되는 것 같습니다! max-width로 설정하였는데 왜 그런 걸까요? 4번에 질문한 문제의 경우 이것과 관련이 있을까요..? 어떻게 해결해야 할까요?ㅠㅠ 

6.
처음에 반응형을 어떻게 접근해야 할 지 몰라서 한참을 손을 못 대고 있다가, 다른 분들이 flex:grid로 속성을 바꿔서 미디어쿼리를 적용하면 된다고 하셔서 그제서야 손을 댈 수 있었는데요..
footer부분도 어떻게 해야 할 지 한참 고민하다가 다른 분이 footer에도 grid속성을 사용하신 걸 보고 따라했습니다ㅠ_ㅠ
(저의 머리로는 grid로 정렬하는 방법을 생각해내지 못했을 것입니다,,) 
디자인별 접근 팁..? 같은 게 있을까요?

 잘 모르겠거나 헷갈리는 부분들은 코드에 주석으로 남겨 놓았습니다..!

![메타태그](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/144667455/45dc5333-4650-4ac3-9703-b39f438771ee)

![메타태그-2](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/144667455/68577aa2-8695-4f06-8e7e-ed834875481c)

![제목 없음-1](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/144667455/62e7ab73-d9f2-44d4-81b7-c56a4630131d)

![제목없음-3](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/144667455/a41dbf9d-f32c-4d76-8c40-f377dd661938)

2023-09-26 05:04 UTC, addiescode-sj commented
## 머지 전 필수 체크

<img width="1583" alt="image" src="https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/69444278/0a75ca9f-af3b-4491-9f52-a377091f02f8">


### nav 리팩토링

위 이미지와 같이 태블릿에서 좌우 여백 32px만 남기고 로고와 로그인버튼이 가까워지게 만들려면, nav-container에 적용되어있는 padding을 없애고 nav에 해당 padding값을 적용시켜줘야해요. 그리고 이렇게 했을때 스타일 겹침이 발생하고있기때문에 nav-container에 명시되어있는 padding값도 필요할때만 쓰일 수 있게 다른 미디어쿼리 안으로 명세해주세요. 

### signin, signup form 내부 padding값 적용, margin값 변경
<img width="1062" alt="image" src="https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/69444278/ca3c2031-23bf-42d7-b2cf-4e965ded5566">

이런식으로 form태그에서 좌우 padding값을 주면 안에 있는 요소들이 부모 컨테이너의 padding인 좌우 32px의 안쪽으로 채워지겠죠? 

그리고 margin은 mobile에서는 들어갈 여유가 없어 실질적으로 좌우 margin이 적용되고있지않으므로 margin-top만 써주면 될 것 같아요. 

이외에도 max-width로 준건데도 form 400px 적용이 되고, 박스 중앙정렬 안된다고 질문 주셨는데, 구현한 의도대로 잘 작동하고있네요 :) 한번 체크해주세요.

2023-09-26 05:24 UTC, addiescode-sj requested changes
혜윤님, 코드를 깔끔하게 잘 작성해주고 계시네요!
몇가지 도움될만한 코멘트를 남겨드렸어요. 확인하시고, 수요일까지 수정하면 머지해드리겠습니다 :)

2023-09-26 05:24 UTC, addiescode-sj commented on index.html
> +    <meta property="og:image" content="./images/IMG7248.jpg">
로컬에 있는 이미지말고 웹상에 호스팅된 이미지 url을 활용해봐요 :)

2023-09-26 05:24 UTC, addiescode-sj commented on index.html
> +        <div class="nav-container">
이 경우 사실상 nav-container의 역할이 nav태그가 하는 역할과 똑같지 않나요?
불필요하게 div로 한번 더 감싸줄 필요가 없을 것 같아요 :) 

nav아래에 바로 자식 요소들이 위치해줘도 무방할것같네요.

2023-09-26 05:24 UTC, addiescode-sj commented on index.html
> +            <span class="head-title-gradient">세상의 모든 정보</span>를<br>
class네임들 정말 깔끔하게 잘 써주셨네요 :)
head-container -> head-title -> head-title-gradient 등으로 뎁스가 깊어질수록 유기적으로 이어지는 네이밍이 보기 정말 편한 것 같아요 :)

2023-09-26 05:24 UTC, addiescode-sj commented on index.html
> +        <div class="wrapper">
wrapper는 너무 일반적인 것 같아요. 
이미지를 담고 있는 wrapper div라면 thumb-wrapper등으로 조금 더 구체적으로 이 엘리먼트가 어떤 역할을 하는지 나타내주는건 어떨까요?

2023-09-26 05:24 UTC, addiescode-sj commented on index.html
> +        <div class="wrapper">
그냥 일반적으로 이미지를 담고있는 wrapper div의 역할만 담당하고싶다면 아예 클래스이름을 안지어주는 방법도 있겠네요 :)

2023-09-26 05:24 UTC, addiescode-sj commented on index.html
> +      <div class="footer-section">
이 부분도, 아까 nav태그에서 설명했던것처럼 불필요하게 뎁스가 깊어지는 것 같아요.
.footer-section을 footer태그에서 써주고 불필요한 div는 없애주는게 어떨까요?

2023-09-26 05:24 UTC, addiescode-sj commented on styles/index.css
> +  max-width: 1920px;
오호, max-width와 width를 적절하게 사용하실 줄 아시는군요! ㅎㅎ
다만 width: 100%가 max-width: 1920px보다 우선 적용된다는 점 참고해주시면 될 것 같아요 :)

2023-09-26 05:24 UTC, addiescode-sj commented on styles/signin.css
> +  margin: 14.875rem 0 7.25rem 0;
흠, index.css에서는 px을 썼는데 signin.css는 rem을 활용하셨네요?
그런데 rem을 쓰는 이유는 상대적으로 root font size에 따라 가변이 되게끔 만들어주기위해 쓰는거라서
이 페이지에서만 쓰는게 아닌 전체적으로 단위 적용을 해주시는게 목적에 맞게 활용할 수 있는 방법이 될 것같아요.

그리고 지금 default font size인 16px기준으로 rem을 변환해 쓰는것같은데,
이렇게 하면 계산하기 힘드니까 다음부터는 default font size를 10px로 바꿔서 rem을 적용하고, 모든 css파일에 적용하는것을 원칙으로 삼으면 어떨까요?

root element인 html을 select해서 font-size를 바꿔주시면 됩니다 :)

2023-09-26 05:24 UTC, addiescode-sj commented on styles/signin.css
> +  /* 모바일 사이즈에서 좌우로 여백 32px를 두고 내부 요소들이 모바일 사이즈에 맞게 함께 줄어들어야 할 것 같은데
이 부분에 대한 코멘트도 별개 코멘트(머지 전 체크)에서 언급해드렸습니다 :)

2023-09-27 09:11 UTC, addiescode-sj commented
수고하셨어요!! 리뷰 내용 모두 다 반영해주셨네요 습득력이 좋으세요 :)

2023-09-27 09:11 UTC, merged

2023-09-27 09:32 UTC, hyeyoonS commented on index.html
> +    <meta property="og:image" content="./images/IMG7248.jpg">
웹에 먼저 올려야 하는 줄 몰랐어요..!! 수정했습니다~.~

2023-09-27 09:34 UTC, hyeyoonS commented on index.html
> +        <div class="nav-container">
시맨틱태그는 안에 있는 내용들을 담아줄 컨테이너가 꼭 있어야 하는 줄 알았습니다 ㅠㅠ  그래서 footer에도 footer-section을 만들었었습니다,, 수정했습니다 !!

2023-09-27 09:35 UTC, hyeyoonS commented on index.html
> +        <div class="wrapper">
앗 네이밍 수정했씁니다~.~!!

2023-09-27 09:37 UTC, hyeyoonS commented on styles/signin.css
> +  margin: 14.875rem 0 7.25rem 0;
reset.css 파일에
:root {
   font-size: 60%;
}
추가하고 10px = 1rem 을 기준으로 단위 수정했습니다 !

2023-09-27 09:39 UTC, hyeyoonS commented on styles/signin.css
> +  /* 모바일 사이즈에서 좌우로 여백 32px를 두고 내부 요소들이 모바일 사이즈에 맞게 함께 줄어들어야 할 것 같은데
이부분 드뎌 이해가 되었어요,,,,ㅠㅠ 마진이랑 패딩값이 개념들이 헷갈려서 막 사용하다보니 저렇게 됐습니다ㅠ_ㅠ 수정했습니다 ~!~!