Part1 이승연 week2
codeit-bootcamp-frontend/1-Weekly-Mission pull request #15
Opened 2023-09-15 03:02 UTC by orrhrr

## 요구사항

### 기본

- [x] 2주차 부터는 Github에 PR(Pull Request)을 만들어 주세요. (참고: Github 가이드 문서 링크 필요)
- [x] Netlify에 파일 배포가 아닌 포크한 Github 레포지토리와 연결해 주세요.
- [x] 아래로 스크롤 해도 “Linkbrary” 로고와 “로그인” 버튼이 있는 상단 네비게이션 바(Global Navigation Bar)가 최상단에 고정되게 해주세요.
-[x] 피그마 디자인에 맞게 PC사이즈 로그인 페이지를 만들어 주세요.
-[x] 로그인 페이지의 url path는 ‘/signin’ 입니다.
-[▵] 피그마 디자인에 맞게 PC사이즈 회원가입 페이지를 만들어 주세요.
-[x] 회원가입 페이지의 url path는 ‘/signup’ 입니다.
-[x] React와 같은 UI 라이브러리를 사용하지 않고 진행합니다. 

### 심화

- [x] palette에 있는 color값들을 css 변수로 등록하고 사용해 주세요.
- [x] 비밀번호 input 요소 위에 비밀번호를 확인할 수 있는 아이콘을 추가해 주세요.

## 주요 변경사항

- 
-

## 스크린샷

- signin page
![스크린샷 2023-09-15 오전 11 43 48](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/120437902/8050e51a-54e7-4d4d-95bf-1e0e1e35a1b0)

-signup page
![스크린샷 2023-09-15 오전 11 43 27](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/120437902/16917666-14e8-4272-a49b-e17b2a288217)

## 멘토에게

- 어제 멘토링 주신 대로 section에 height를 100vh로 설정하였으나, 처음부터 브라우저 창이 작게 열릴 경우 브라우저 크기 변경시 배경색 짤림 현상이 지속되었습니다. 일단은 픽셀값으로 고정해두었습니다. 3주차 반응형 웹 강의를 듣고 다시 수정할 예정입니다. 
- 템플릿 코드를 보고 나니 제 css 코드가 지나치게 길게 느껴졌습니다. 지금부터 다듬어나가는게 좋을지 아니면 일단 프로젝트를 마친 후 새롭게 리팩토링 하는게 좋을지 궁금합니다.
- HTML로 화면구성을 기획해 나갈 때 효율적인 방식이 어떤것인지 궁금합니다. HTML 작성 후에 css 적용하다보면 다시 HTML을 변경하게 되더라구요..시간이 낭비되는것 같아서 질문드립니다.
- 보통 과제정도의 웹페이지를 만드는데 시간이 어느정도 걸리는지 궁금합니다. 코린이다 보니 제가 작성한 코드를 왔다갔다 하면서 보는데도 시간이 너무 오래걸리는것 같아서 조금 조바심이 듭니다..
-이번 과제는 flex만 사용하였는데 gird로 틀을 잡아두고 안에 있는 요소들을 flex로 조정하는 것이 더 나을까요?

2023-09-18 05:55 UTC, addiescode-sj commented
저한테 따로 주신 질문에 대한 답 먼저 코멘트해드리겠습니다 :)

<img width="939" alt="image" src="https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/69444278/8aa6875e-d821-49de-94bf-54df919a16b1">

- signin, signup 페이지에 대한 배경색 짤림의 경우 section에서 margin값으로 아래위 여백을 주는게 아니라 padding값으로 바꿔주시고 margin: 0 auto로 가운데 정렬시켜주는 방식으로 바꿔보실래요? section에 주셨던 고정 height와 height 속성값 모두 빼주세요! 

- css코드가 길게 느껴지는 이유도 혹시 생각해보셨나요~? 제가 코드 리뷰하면서 이유가 보인다면 따로 코멘트 남겨두겠습니다. 제출하신 위클리 미션의 경우 수요일 7시전까지 수정할 시간을 드리고 일괄적으로 머지해드릴 예정이니, 코드 리뷰에 대한 반영 & 수정 모두 가능한 점 참고해주세요. 보통은 html작성을 하고 css를 적용하게되는게 맞는데, 아직 레이아웃을 짤 때 어떤 걸 기준으로 어떻게 적용해야할지에 대한 체화가 덜 돼서 그런걸수도있어요. 저의 경우 마크업을 할때 엘리먼트가 본연의 용도에 맞게 잘 쓰였는가를 1차로 중요하게 보고 덩어리처럼 보이는 ui요소들이 있다면 한 영역으로 구분해주면서 코드를 최대한 재사용하지않기위해 노력하는 편입니다. 

- 조바심내지 않으셔도 됩니다! 매주 소화해야하는 내용을 잘 소화하고 계세요 :) 속도는 익숙해지면 느는거니까요! 

- grid는 정렬기준이나 배치기준이 flex를 쓸때보단 조금 복잡할 때 쓰는 편이예요. 지금 ui는 flex만 써도 충분하게 느껴집니다 :) 과제에 적용하는것보다는 따로 개인공부하면서 grid를 연습해보세요!

2023-09-18 10:00 UTC, addiescode-sj requested changes
승연님~ 너무 수고하셨어요.

전반적으로, 저한테 질문주신 것처럼 확실히 불필요한 css코드를 많이 쓰셨네요.
default value는 안써도 되고, 초반에 css초기화를 하는걸로 불필요한 코드를 많이 줄일 수 있을것같아요.

그리고 width, height등에 고정값을 써주면 반응형을 고려할때 제대로 동작하지않을 가능성이 높아져서,
고정값을 쓰지않고 min-height, max-height등 최소/최대값만 고정하는걸로 원하는 디자인대로 구현되도록 연습해보시면 좋을 것 같네요.

우선 불필요한 공백과 css 제거하면서 파일구조도 조금 바꿔보세요!
이 부분에 대한 반영만이라도 수요일까지 정리 해주시면 Approve & 머지 해드리겠습니다 :)

2023-09-19 11:32 UTC, orrhrr commented on style.css
> +    z-index: 1;
z-index를 지웠더니 브라우저 크기를 줄였을 때, 다른 요소들에 헤더요소들이 가려져서 다시 넣었습니다..ㅠ
header 태그와 main 태그가 부모자식 관계가 아니라 형제관계라 그런것일까요?

2023-09-19 11:43 UTC, orrhrr commented on style.css
> +    display: inline-flex;
gap에 있는 음수는 오타여서 수정했습니다!
그리고 inline-flex를 없애봤는데 가로가 아닌 세로로 정렬이 됩니다.
부모 요소들 중에 flex-direction을 건든 요소는 없었습니다.
바로 상위 부모태그에 width와 height가 정해져있는데, 
부모태그보다 크기가 커서 자동으로 세로 정렬 된걸까요?

2023-09-19 12:33 UTC, orrhrr commented on style.css
> +    width: 400px;
피그마 시안에서 로그인 창을 담은 div태그 width가 400px로 지정 되어있는데, 이 부분도 정렬로 맞춰야 하는걸까요?

2023-09-20 00:53 UTC, addiescode-sj commented on style.css
> +    width: 400px;
네 디자인 그대로 구현하되, 스크린사이즈에 따라 달라질것같은 가변 박스는 크기 지정을 고정값으로 해주지않고 min-width, max-width등과 같이 최소 최대값만 지정해주는 편이예요 ~ :) 즉 반응형을 고려해 width로 고정값을 넣어주는것보단 이 두 프로퍼티를 이용해서 크기를 고정해주시는게 좋습니다!

2023-09-20 01:07 UTC, addiescode-sj commented on style.css
> +    display: inline-flex;
아하, wanted-link-cards의 flex item이 cards-frame하나네요. 이럴 경우 wanted-link-cards에서는 flex를 써줄 필요가없죠?  flexbox 속성들을 제거하고, cards-frame에서 flex를 쓰시면 돼요.

`display: inline-flex -> display: flex`로 변경하시면 됩니다!
기본적인 방향은 row고, 부모 컨테이너보다 크기가 커도 items들이 wrap되지 않는게 기본값이므로 넘치지 않습니다 :)

2023-09-20 01:09 UTC, addiescode-sj commented on style.css
> +    z-index: 1;
다른 엘리먼트에서 z-index를 올려줬네요! 보통 이런건 floating element라고 UI에서 부르는데, floating element의 z-index는 항상 최상위가 되어야 하니까 최대값인 999를 적용해주시는게 좋을 것 같습니다 :)

2023-09-20 10:02 UTC, merged