[이슬] week7
codeit-bootcamp-frontend/1-Weekly-Mission pull request #287
Opened 2023-10-17 11:52 UTC by olseul

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-10-24 00:46 UTC, addiescode-sj requested changes
이슬님 리액트 잘하시는데요? ㅎㅎㅎ
몇가지 도움될만한 코멘트 드렸어요.

디렉토리 구조의 경우 다른분들도 헷갈려하시는거라 제가 예시를 멘토링시간때 좀 보여드리도록할게요.
수요일까지 디렉토리 구조만 살짝 바꿔서 머지해볼까요? 일단 Request Changes드려보고, 반영해주시면 확인 후 머지하겠습니다! part2 첫번째 미션 너무 수고하셨어요~ 👍

2023-10-24 00:46 UTC, addiescode-sj commented on src/App.js
> +const App = () => {
쭉 보니 컴포넌트를 화살표함수를 써서 만들거나 function 키워드를 써서 만드는게 혼재되어있는것같아요! 의도하신거라면 이슬님의 기준이 있을까요?

2023-10-24 00:46 UTC, addiescode-sj commented on src/App.js
> +    <div>
잘하셨어요 구조가 너무 보기 편하네요 :)

2023-10-24 00:46 UTC, addiescode-sj commented on src/Card.js
> +const timeDifference = (current, previous) => {
함수 너무 깔끔하게 만들어주셨어요! 좋아요 ㅎㅎ
다만 이런 함수는 Card컴포넌트에서만 쓰이기보다는 여기저기에서 재사용될 가능성이 많아보여요.
이런 함수는 공용으로 빼두는게 어떨까요? 저라면 src > utils 폴더를 만들어서 그 아래에 이 함수를 담고 파일을 만들어줄것같네요!

2023-10-24 00:46 UTC, addiescode-sj commented on src/Card.js
> +  if (elapsed < msPerMinute) {
조건이 많아서 else if가 늘어났고 가독성이 조금 떨어지는것같아요. 
이런 경우 switch문으로 대체하거나, early return 기법을 써서 조건문을 체크할때 좀더 명확하게 분리해보는건 어떨까요?

[참고](https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90)

2023-10-24 00:46 UTC, addiescode-sj commented on src/Card.js
> +        <span className="date">{timeDifference(currentTime, createdAt)}</span>
저라면 `timeDifference(currentTime, createdAt)` 리턴값을 담아주는 변수 하나를 만들어서 이 안에는 그 변수를 써줬을것같아요. 그러면 보이는 jsx코드가 더 깔끔해지겠죠?

2023-10-24 00:46 UTC, addiescode-sj commented on src/Card.js
> +const Card = ({ link }) => {
link가 undefined인 경우도 한번 생각해주시면 좋을것같아요!

2023-10-24 00:46 UTC, addiescode-sj commented on src/CardList.js
> +const CardList = () => {
CardList > Card 유기적으로 이어지는 네이밍 너무 좋네요 👍

2023-10-24 00:46 UTC, addiescode-sj commented on src/FacebookIcon.js
svg코드를 컴포넌트로 만드셨군요! 아주 좋아요.
다만 이건 src바로 밑에 있으면 안될것같아요.

전체적으로 디렉토리 구조가 조금 애매한것같은데, 이건 다른분들도 충분히 헷갈려하실수있을 것 같아서
제가 생각하는 이상적인 디렉토리 구조에 대해서 추후에 멘토링 드려볼게요 :)

2023-10-24 00:46 UTC, addiescode-sj commented on src/FolderOwnerInfo.js
> +  const [ownerName, setOwnerName] = useState("");
이런건 state하나에 객체로 묶어두는게 편하지않을까요~? ㅎㅎ
나중에 setState로 업데이트시킬때에만 깊은복사, 얕은 복사 개념을 잘 알고 활용해주시면 된답니다.
관리하기 편하게 객체로 바꿔보세요!

2023-10-24 00:46 UTC, addiescode-sj commented on src/Footer.js
> +            <a
같은 구조가 계속 반복되고있네요?
children을 받는 템플릿 컴포넌트를 하나 만들어서 map으로 돌려주면 더 간결해보이지 않을까요?
나중에 해당 컴포넌트를 재사용할수도있고요!

2023-10-24 00:46 UTC, addiescode-sj commented on src/Navbar.js
> +  const [userData, setUserData] = useState(null);
오호 여기선 개별값 업데이트하지않고 하나로 잘 넣어주셨네요!

2023-10-24 00:46 UTC, addiescode-sj commented on src/SearchBar.js
> +    console.log("검색어:", searchTerm);
PR올리실땐 console.log 찍어보신것도 정리해주세요! ㅎㅎ

2023-10-24 06:57 UTC, addiescode-sj commented
## 멘토의 답변

- 폴더 구조가 헷갈려서 일단 죄다 src에 넣긴 했는데 어떤식으로 관리하는 게 좋을까요?
- svg파일도 컴포넌트로 만들어서 관리했는데 assets폴더에다가 .svg파일로 보관하는 게 좋을까요?

위 두가지 질문 다 멘토링 시간에 커버해드렸습니다!
추가적으로 궁금한점 생기시면 이 아래에 코멘트해주세요 :)

2023-10-24 11:19 UTC, olseul commented
말씀해주신 부분 다 수정했습니다!
다만 폴더 구조는 한번 더 피드백 해주실 수 있나요?
이 정도면 괜찮은 건가요?🤔

2023-10-25 05:06 UTC, addiescode-sj approved these changes
@olseul 
네! 구조 좋습니다 수고하셨습니다 ㅎㅎ

2023-10-25 09:52 UTC, merged