Part2 홍재원 week7
codeit-bootcamp-frontend/1-Weekly-Mission pull request #291
Opened 2023-10-21 15:25 UTC by Hongjw030

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)
- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?
- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?
- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?
- [x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?
- [x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?
- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?
- [x] 카드 컴포넌트에서 createdAt 데이터 기준으로 현재 Date와 차이에 따라 아래와 같은 규칙으로 설정했나요?
2분 미만은 “1 minute ago”
59분 이하는 “OO minutes ago”
60분 이상은 “1 hour ago”
23시간 이하는 “OO hours ago”
24시간 이상은 “1 day ago”
30일 이하는 “OO days ago”
31일 이상은 “1 month ago”
11달 이하는 “OO months ago”
12달 이상은 “1 year ago”
OO달 이상은 “{OO/12(소수점 버린 정수)} years ago”
- [x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?
- [x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화
-[x] 커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

- 리액트로 각 컴포넌트를 만들어 sharing 페이지를 구현했습니다.
- sample/user api를 받아와 처리했습니다.

## 스크린샷

![image](이미지url)

## 멘토에게
- 2분 미만, 1시간 미만... 이 코드를 짜는데 너무 코드가 길어지고 제가 좀 비효율적으로 짠다는 느낌을 받았습니다. 혹시 더 깔끔하게 코드를 고칠 방법은 없을까요?
- card 컴포넌트에서 구현하고 싶었던 건 card 컴포넌트 자체에 마우스를 올릴 때 이미지가 확대되는 거였는데, 그러려면 css 선택자를 어떻게 써야 할지 모르겠습니다..!! 
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

감사합니다!! :D

2023-10-23 02:38 UTC, addiescode-sj requested changes
재원님~ 걱정이 많으셔서 리액트 코드 작성에 큰 어려움을 느끼시는건가 걱정했는데 잘 하시네요!
다만 앞으로 규모가 확장될 가능성을 고려해 css파일들의 위치를 바꾸셨으면 좋겠고 (이게 전체적으로봤을때 제일 큰 리팩터링 포인트가 될것같아요 :) 네트워크 요청에 대한 응답을 받아서 처리할때 에러 핸들링까지 해주시면 좋을것같습니다. 

우선 이 두개에 대한 반영이 머지 전에 우선적으로 이뤄지면 좋을 것 같아, Request Changes 드리겠습니다. 수고하셨어요! 코멘트 읽으시면서 이해 안되는 부분은 저 멘션해서 대댓글 달아주세요~ :)

2023-10-23 02:38 UTC, addiescode-sj commented on src/components/Card.js
> +  if (!cardList) {
굳 👍 이런 꼼꼼한 처리 너무 좋아요!

2023-10-23 02:38 UTC, addiescode-sj commented on src/styles/app.css
styles아래에 있는 css파일들은 모든 컴포넌트에서 사용할수있는 공용파일만 위치시켜두는게 맞아보여요. (e.g reset.css)
왜냐하면 사용하고자하는곳에서 가까운곳에 필요한 파일을 둬야 나중에 프로젝트 규모가 커지더라도 보기 쉽게 관리할 수 있거든요 :)

혹시 footer.css, header.css같이 개별 컴포넌트에서만 쓰이는 css파일들은 
components > Card > Card.js, Card.style.css 와 같이 네이밍 규칙을 일관적으로 정해서 두는게 어떨까요?

2023-10-23 02:41 UTC, addiescode-sj commented
## 멘토의 답변

### 2분 미만, 1시간 미만... 이 코드를 짜는데 너무 코드가 길어지고 제가 좀 비효율적으로 짠다는 느낌을 받았습니다. 혹시 더 깔끔하게 코드를 고칠 방법은 없을까요?
관련해서 PR본문에 코멘트 달아드렸습니다 :)

### card 컴포넌트에서 구현하고 싶었던 건 card 컴포넌트 자체에 마우스를 올릴 때 이미지가 확대되는 거였는데, 그러려면 css 선택자를 어떻게 써야 할지 모르겠습니다..!!
hover이벤트를 선택자에서 잡아주거나, jsx내에서 onHover 이벤트 처리를 시도해보실래요? ㅎㅎ

2023-10-25 04:29 UTC, Hongjw030 commented on src/styles/app.css
자세한 피드백 너무 감사드립니다!!

우선 아래 과정을 처리했습니다,

1. src 하위에 api 폴더를 만들어 api.js를 모아둠
2. components 폴더 아래에 component 당 폴더를 만들어 css와 같이 모아둠
3. css 파일 이름들을 {컴포넌트명}.style.css 로 모두 바꿈

그런데 App은 컴포넌트긴 한데 재사용할 때 쓰이는 컴포넌트라기보단 컴포넌트를 하나로 모아주는 box 컴포넌트의 느낌인데요, App 컴포넌트도 components 폴더 아래에 App 폴더를 만들고 따로 관리해주는 게 좋을까요??

2023-10-25 04:48 UTC, addiescode-sj commented on src/styles/app.css
아니요 App.js는 그냥 src아래에 바로 두셔도 무방할것같습니다! :)

2023-10-25 05:10 UTC, Hongjw030 commented on src/styles/app.css
감사합니다!!

2023-10-25 05:23 UTC, Hongjw030 commented on src/App.js
> +    const { name: userName, email, profileImageSource } = await getUser();
안녕하세요 강사님!! 에러 핸들링을 하기 위해

1. hooks 폴더에 useAsync 라는 커스텀 훅을 만들고
2. App.js 에서 async 문 내부에 훅을 사용함
3. isLoading, loadingError 변수를 만들어 받아오고, App.js 의 return 문에 해당 메세지가 조건부로 렌더링되게 추가

를 했는데, 혹시 올바르게 코드를 짰는지 봐주실 수 있을까요? 일단 제 컴퓨터 상에서는 문제가 없었기에  push 했습니다!!

2023-10-25 05:25 UTC, addiescode-sj commented on src/App.js
> +    const { name: userName, email, profileImageSource } = await getUser();
깔끔하네요! 너무 잘 하셨어요 👍

2023-10-25 05:25 UTC, addiescode-sj approved these changes

2023-10-25 05:26 UTC, Hongjw030 commented on src/App.js
> +    const { name: userName, email, profileImageSource } = await getUser();
감사합니다!!!! XD !!!!

2023-10-25 06:31 UTC, Hongjw030 commented on src/App.js
> +    setFolderUserProfileImage(folder.owner.profileImageSource);
피드백 감사합니다 강사님!!

해당 코드를 고쳐봤는데 이렇게 고쳐도 될지 모르겠습니다.

의도한 바:
1. props 에 default 값을 주어 객체에 해당 props가 없다라도 값이 설정되게 함.
2. 어차피 (App.js 37줄) `    if (!folderResult || !userResult) return;` 코드가 있으니 folderResult가 userResult가 undefined or null인 상황은 생각하지 말고, 무조건 값이 있다고 생각함. 그래서 (App.js54줄)  `    const { name = "", owner = null, links="" } = folderResult.folder;` 에는 옵셔널 체이닝을 쓰지 않음.
3. (App.js 55~60줄) folderResult.folder 의 내부 프로퍼티 owner이 존재할지 안할지 모르니 여기서는 옵셔널 체이닝을 씀.

위 세가지를 의도하고 코드를 짰는데, 적절한 사고방식(?) 일까요? 감사합니다!

2023-10-25 09:47 UTC, addiescode-sj commented on src/App.js
> +    setFolderUserProfileImage(folder.owner.profileImageSource);
@Hongjw030 재원님 이 코멘트 제가 미처 확인을 못해서요! 다음 PR 올리실때 따로 코멘트 남겨주시면 확인해드릴게요 :) 
그리고 다음부터는 저를 mention해주셔야 더 빨리 확인이 가능합니다 ㅎㅎ 참고해주세요~!

2023-10-25 09:50 UTC, merged

2023-10-25 10:29 UTC, Hongjw030 commented on src/App.js
> +    setFolderUserProfileImage(folder.owner.profileImageSource);
넵 감사합니다!!!!   :D