[김윤후] week7
codeit-bootcamp-frontend/1-Weekly-Mission pull request #301
Opened 2023-10-22 06:04 UTC by K-Y-Hoo

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)
- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?
- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?
- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?
- [x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?
- [x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?
- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?
- [x] 카드 컴포넌트에서 createdAt 데이터 기준으로 현재 Date와 차이에 따라 아래와 같은 규칙으로 설정했나요?
- [x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?
- [x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- [x] 커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

-

## 스크린샷

## 멘토에게

- 브라우저 화면 크기가 바뀔 때 카드 컴포넌트의 위치가 조금 어색합니다. css 수정을 어떻게 해야할 지 궁금합니다.
- 카드 컴포넌트 api 데이터를 받아올 때 useState를 통해서 데이터의 값을 변수에 할당했는데요, 반복문으로 9개의 카드 컴포넌트를 구현하였는데 이때문에 서버에 데이터 요청을 9번 보내게 되었습니다. 한번의 요청만으로 9개의 카드 컴포넌트에 각각의 데이터를 할당할 방법이 궁금합니다.
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-10-23 08:02 UTC, addiescode-sj requested changes
윤후님, 우선 꼼꼼한 처리와 센스가 돋보이시네요 👍 
다만 제가 아쉬웠던 점이 하나 있다면, 컴포넌트에 데이터를 내려주기위한 api를 호출하는 명확한 시점과 장소가 조금 헷갈리셨던것같아요. 코멘트 내에서 자세히 설명드렸으니, 읽어보시고 이번주 수요일 머지 전까지 우선적으로 반영해주시면 좋을 것 같네요! 이점이 아쉬워서 우선 Request Change드려보도록하겠습니다.

위클리미션 수고하셨습니다!

2023-10-23 08:34 UTC, addiescode-sj commented
## 멘토의 답변

### 브라우저 화면 크기가 바뀔 때 카드 컴포넌트의 위치가 조금 어색합니다. css 수정을 어떻게 해야할 지 궁금합니다.

네, css확인해보니 ul밑에 li에서 max-width로 카드 width의 최대값을 고정해주시고 a태그에 고정 width로 넣은 `width: 41.8rem;` 을 제거해주시면 원하는 대로 Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치가 될것같네요. 참고해주세요! :) 

### 카드 컴포넌트 api 데이터를 받아올 때 useState를 통해서 데이터의 값을 변수에 할당했는데요, 반복문으로 9개의 카드 컴포넌트를 구현하였는데 이때문에 서버에 데이터 요청을 9번 보내게 되었습니다. 한번의 요청만으로 9개의 카드 컴포넌트에 각각의 데이터를 할당할 방법이 궁금합니다.
PR 본문 내에서 코멘트 드렸습니다 :)

2023-10-25 05:03 UTC, addiescode-sj commented on src/ui/Header.js
> +  const getFullFolderData = useCallback(async () => {
@K-Y-Hoo 

윤후님 getFullFolderData useCallback를 만들고 아래 getFullFolderData dependency를 갖는 useEffect를 만든 이유는 어떤 요구사항/ 문제를 해결하려고하신걸까요~? useCallback은 매 렌더링때마다 인스턴스가 생기는 함수를 memoize하기 위해 쓰는데요, dependency list에 빈 배열을 넣어주셨으니 useEffect가 컴포넌트가 처음 마운트 될때만 호출되고 그 이후에 리렌더링되게되면 해당 함수의 인스턴스가 다시 생성되어 실행되지않을거예요. 결국 아래 useEffect도 똑같은 시점에 호출되게되겠죠? 

getFullFolderData에서 해주는 일은 결국 full data state를 업데이트시켜주는일인데, 

```jsx
  useEffect(() => {
    getFolderOwner();
  }, []);
```
이 일은 위에 있는 useEffect에서도 충분히 처리할수있고 api 호출을 무의미하게 두번 나눠서 할 필요가 없어보입니다.
특별한 의도가 있었던거라면 알려주세요!

2023-10-25 05:38 UTC, K-Y-Hoo commented on src/ui/Header.js
> +  const getFullFolderData = useCallback(async () => {
특별한 의도가 있었던 것은 아닙니다. useEffect와 useCallback의 차이점을 잘 숙지하지 못하고 사용하게 되었습니다. 리팩토링해서 다시 커밋 올리겠습니다!

2023-10-25 05:45 UTC, K-Y-Hoo commented on src/ui/Header.js
> +  const getFullFolderData = useCallback(async () => {
말씀해주신대로 별다른 의미 없이 api 호출을 두 번 하고 있었네요. 미처 신경을 못썼습니다.

2023-10-25 06:37 UTC, addiescode-sj approved these changes
수고하셨습니다!

2023-10-25 09:51 UTC, merged