[강현지] Week7
codeit-bootcamp-frontend/1-Weekly-Mission pull request #326
Opened 2023-10-22 15:03 UTC by kanglocal

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터는 랜딩 페이지와 동일한 스타일과 규칙으로 만들어 주세요. (week 1 ~ 3 요구사항 참고)
- [x] 카드 컴포넌트를 클릭하면 해당하는 링크로 새로운 창을 띄워서 이동하게 해주세요.
- [x] 카드 컴포넌트에서 createdAt 데이터 기준으로 현재 Date와 차이에 따라 아래와 같은 규칙으로 설정해 주세요.
- 2분 미만은 “1 minute ago”
- 59분 이하는 “OO minutes ago”
- 60분 이상은 “1 hour ago”
- 23시간 이하는 “OO hours ago”
- 24시간 이상은 “1 day ago”
- 30일 이하는 “OO days ago”
- 31일 이상은 “1 month ago”
- 11달 이하는 “OO months ago”
- 12달 이상은 “1 year ago”
- OO달 이상은 “{OO/12(소수점 버린 정수)} years ago”
- [x] 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용해 주세요.
- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용해 주세요.
- [x] Static, no image, Hover 상태만 고려해 카드 컴포넌트를 만들어 주세요.
- [x] Hover 상태에서 이미지가 기존 크기의 130%로 커지게 해주세요.
- [ ] 프로필 데이터가 없는 경우 “로그인” 버튼이 보이게 해주세요.
- [ ] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치해 주세요.
- [ ] Tablet, Mobile에서 검색바, 카드 리스트의 좌우 최소 여백은 32px로 설정해 주세요.

### 심화

- [x]
- []

## 주요 변경사항
- React Project로 변경
- Card Component 추가

## 스크린샷

![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/96380950/41b8972a-5a98-4bbf-a5dd-6d864ace0150)

## 멘토에게

- 아직 정리와 완성을 하지 못해서 보기 힘드실테니 가볍게만 읽어봐주시길 바랍니다..

2023-10-25 00:43 UTC, addiescode-sj requested changes
현지님~! 미완성이라고 하셨는데, 그래도 조금만 더 하시면 완성될것같아요!
이번주 위클리미션 보강하고싶으시면 다음주 위클리미션 제출할때 refactor커밋 쌓아주세요, 한꺼번에 봐드릴게요 :)

리액트 자체를 쓰는데에는 문제가 없을정도로 잘 이해하고 열심히 따라와주시고 계시네요 👍 
수고하셨습니다!! 

몇가지 머지전에 우선적으로 반영되면 좋은 요구사항들을 제안드려볼게요!

1. 이미지url을 export하는 파일 : jsx,js구분없이 쓰고계시는데 Pascal case여서 컴포넌트인줄알았어요. 제생각에 이 파일은 constants라는 폴더를 만들어서 상수를 만들어 export하는게 맞아보입니다 :)

2. App.js에서 무의미한 분기문: `return true ? <Home /> : <Landing />;` 이 부분 fallback을 설정해주고싶었던거면 Suspense를 써주세요. 아니라면 무의미한 분기문이 쓰여있으니 Home 컴포넌트만 리턴해주세요 :)

이번주도 너무 수고하셨습니다! 👍

2023-10-25 00:43 UTC, addiescode-sj commented on src/components/Card.js
> +function Card(data) {
props를 받아올때 
```suggestion
function Card({ data }) {
```

이런식으로 받아오면 바로 밑 라인에서 data에서 data를 destruction할 필요가 없어지겠죠?

2023-10-25 00:43 UTC, addiescode-sj commented on src/components/Card.js
> +            src={imageSource ?? NoImage}
오호! Nullish coalescing operator 잘쓰셨네요 ㅎㅎ 굳 👍

2023-10-25 00:43 UTC, addiescode-sj commented on src/components/Card.js
> +          <p className="time-stamp">{formatDateDiff(createdAt)}</p>
이것도 변수로 만들어서 써주면 어떨까 싶네요? 저는 jsx코드는 최대한 깔끔하게 보여야한다고 생각해서요 ㅎㅎ ex. `const timeStamp = formatDateDiff(createdAt)`

2023-10-25 00:43 UTC, addiescode-sj commented on src/components/CommonImages.js
오호, 이 경우 사실상 이미지 URL을 담고있는 상수를 만들어서 해당 상수를 리턴해주는게 맞는것같다는 생각이들어요.
현재 jsx/ js 구분없이 components 아래에 들어가있고, Pascal case로 작성되어있으니 당연히 컴포넌트일거라고 생각했어요.
디렉토리 구조랑 파일이름만 봐도 용도가 명확히 구분되면 좋은데요!

이 파일을 src > constants 아래에 commonImgMap.js라는 파일로 만들고
`const logo = LogoImg;`와 같이 상수로 바꿔서 export해주는건 어떨까요?

2023-10-25 00:43 UTC, addiescode-sj commented on src/components/home/Home.js
> +import React, { useEffect, useState } from 'react';
흠 나중에 importOrder도 정리해볼까요? 
`.prettierrc` 파일을 만드시고, importOrder 옵션으로 만들어주실수 있어요.
저는 이런식으로 쓰고있답니다 :) 

```
"importOrder": [
    "^@(store|modules)/(.*)$",
    "^@(contexts|hoc)/(.*)$",
    "^@hooks/(.*)$",
    "^@constants/?(.*)$",
    "^@pages/(.*)$",
    "^@modals/(.*)$",
    "^@(components|icons)/(.*)$",
    "^@utils/(.*)$",
    "^@styles/(.*)$",
    "^[./]"
  ]
```

2023-10-25 00:43 UTC, addiescode-sj commented on src/api.js
src바로 아래에 api.js가 있는게 조금 어색해보여요! ㅎㅎ
`src > api > api.js` 로 파일 옮겨주시면 좋을 것 같네요 :)

2023-10-25 00:43 UTC, addiescode-sj commented on src/components/home/Images.js
이 파일에서도 위에서 코멘트드린것처럼 파일이름바꿔주시고 상수를 담아주세요! :)

2023-10-25 00:43 UTC, addiescode-sj commented on src/components/landing/Images.js
ㅎㅎㅎ 여기도 추가! ㅎㅎ

2023-10-25 00:43 UTC, addiescode-sj commented on src/components/landing/Landing.js
> +        <section className="save">
이 section들도 똑같은 구조가 반복되고있지않나요~?
children을 받는 템플릿 컴포넌트를 만들어서 jsx가 더 깔끔하게 보일수있도록 구조를 좀 잡아줘볼까요? ㅎㅎ

2023-10-25 09:50 UTC, addiescode-sj commented
@kanglocal 현지님, 다음 PR올리실때 refactor 커밋 쌓아주시면 한번에 봐드릴게요! :)

2023-10-25 09:50 UTC, merged

2023-10-26 09:20 UTC, kanglocal commented on src/components/App.js
> +  return true ? <Home /> : <Landing />;
로그인이 성공해서 localStroage에 accessToken이 있으면 Home을 보여주고, 없으면 Landing을 보여줘야겠다고 생각했지만 
어떻게 처리해야할지 아직 모르겠어서 일단 과제를 진행하기위해 무조건 Home을 보이게 해둬야겠다는 생각에 작성했습니다! 
다음 PR에는 수정해서 올리겠습니다 :) suspens와 fallback에 대해서도 알아보겠습니다ㅜㅜ

2023-10-26 09:30 UTC, kanglocal commented on src/components/home/Home.js
> +import React, { useEffect, useState } from 'react';
와!! 임포트순서 바꿔주는 방법이 정말 알고싶었어요 감사합니다!!