[홍재원] week8
codeit-bootcamp-frontend/1-Weekly-Mission pull request #346
Opened 2023-10-28 16:08 UTC by Hongjw030

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

- 이상하게 폴더 버튼 (전체 즐겨찾기 같은 것들..)을 두 번 눌러야 작동하는데 왜 이러는건질 모르겠습니다...
- useParams는 나중에 검색창에 키워드를 입력하고 그 키워드를 url에 붙여넣을 때 활용하는 거라 이해해서, 딱히 useParams를 쓰지 않았는데 제가 이해한 게 맞나요?
- FolderPage.js 파일의 setCardList 함수 콜백 으로  ` return [...folderResult?.data, ...prevItem];` 이라 하면 key는 중복될 수 없다며 에러가 납니다. prevItem과 folderResult.data 에서 중복되는 card가 있기 때문에 에러가 난다는 건 알겠는데 어떻게 고쳐야할지 모르겠습니다. 그냥 prevItem을 무시하고 folderResult.data만 가져오면 되는 건가요?

2023-10-30 05:44 UTC, addiescode-sj commented
@Hongjw030 재원님 리뷰드리기전에 conflict 먼저 해결해주세요!

2023-10-30 07:40 UTC, addiescode-sj requested changes
재원님~ 저번주보다 훨씬 좋아진것같은데요 ?
다만 setter function을 다음 렌더때까지 업데이트되게끔 보장하는 식으로 써주시는게 기준이 정해져있지않고 이렇게 쓰면 더 좋겠지? 생각해서 쓰신게 보여요.

prev state랑 비교하지않고도 state update해도 가능한지 일괄적으로 체크하고, 기준을 정해서 이런 방식으로 업데이트 시켜주시는걸 우선적으로 반영해주시면 좋을 것 같네요 :) 

미디어쿼리도 브레이크포인트 안 겹치게 잘 만들어주세요!

이번 주 위클리 미션도 너무 수고하셨습니다~~ 👍

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/CardList/CardList.js
> +          <div key={card.id}>
사실 key를 넣어주기위한 div는 따로 없어도 괜찮아요. Card 컴포넌트에 key를 넘겨줄까요?

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/CardList/CardList.module.css
> +@media (min-width: 1124px) {
미디워쿼리끼리 겹쳐서 스타일 상쇄되는 부분이 없도록 `(min-width:769px) and (max-width: 1125px)`로 바꿔줄까요?

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/FolderHeader/FolderHeader.js
> +import styles from "./FolderHeader.module.css";
import도 순서를 지켜서 써주시면 좋을거예요.
이 [아티클](https://velog.io/@himprover/prettier%EB%A1%9C-%EB%92%A4%EC%A3%BD%EB%B0%95%EC%A3%BD-import-%EC%A0%95%EB%A6%AC%ED%95%98%EA%B8%B0) 참고해보실래요~?

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/FolderHeader/FolderHeader.js
> +              return (
이런 single block을 리턴할때는 {}와 return 모두 생략가능합니다! 참고해주세요 :)

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/FolderHeader/FolderHeader.js
> +                <div key={folder.id} className={styles["folder-button"]}>
여기서도 key={folder.id}로 넣어주기위해 한번 더 div 컴포넌트로 감쌌네요 혹시 이렇게 쓰는 이유가 있을까요~?

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/FolderHeader/FolderHeader.js
> +
불필요한 공백은 삭제해주셔도됩니다 :)

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/FolderHeader/FolderHeader.js
> +    setCardList(() => {
혹시 prev state와 비교해서 넣어줘야하는 특별한 이유가 있을까요?
밑에서 update된 cardList를 바로 써줘야하니까 이렇게 써주신걸까요~?

그냥 state를 spread operator를 써서 업데이트하고, useRef로 저장하지않는다면 어떤 차이가 있나요? :)

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/FolderHeader/FolderHeader.js
> +  const handleButton = (name, id) => {
여기 함수 위에도 빈칸 하나 넣어주세요 :)

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/FolderNameButton/FolderNameButton.js
> +    onChange(name, id);
굳굳 👍

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/Footer/Footer.js
> +        <a
이렇게 같은 구조로 반복되는것은 해당되는 data mapper object로 상수를 써주고 map돌려주는게 훨씬 깔끔해보인답니다 :)

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/LinkAddInput/LinkAddInput.js
> +  const handleKeywordChange = (e) => setKeyword(e.target.value);
굳굳 자식으로 내려주는 함수 활용 잘하시네요 👍

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/MobileFolderButton/MobileFolderButton.js
> +function MobileFolderButton() {
엇 이런 컴포넌트는 body가 너무 작아서 따로 안빼는게 오히려 나을수도..?

2023-10-30 07:40 UTC, addiescode-sj commented on src/components/Nav/Nav.module.css
> +@media (min-width: 768px) {
여기도 미디어 쿼리 겹치는거 없게 잘 만들어주세요!

2023-10-30 07:40 UTC, addiescode-sj commented on src/pages/FolderPage.js
> +    const allFolders = await getAllFoldersAsync();
```suggestion
    const { data as folderList } = await getAllFoldersAsync();
    setFolderList(folderList);
```
이런건 어때요?

2023-10-30 07:40 UTC, addiescode-sj commented on src/pages/SharedPage.js
> +    setFolderValues((prevValues) => {
흠 자꾸 prev value랑 비교해서 업데이트하는 부분이 보이네요.
이거, folderValues를 바로 밑줄에서 소비할 일이 있을때 이런식으로 setter function을 활용해주시면 되세요.
기준을 정해서 state update 시켜주세요 (필요 없는 경우에도 이런식으로 많이 쓴다면 결국 동기실행될때까지 기다리는 타이밍이 합쳐져서 app을 전체적으로 느리게 만드는 원인이 될 수 있답니다)

2023-10-30 07:45 UTC, addiescode-sj commented
코드가 진짜 많이 더럽습니다... 기능 구현만이라도 하자는 생각으로 짜서.. ㅠㅠ 최대한 빨리 리팩토링해보겠습니다.

### useParams 를 써서 폴더 버튼(전체, 즐겨찾기...)에 동적 경로를 할당하고 싶었는데 잘 되지 않았습니다 ㅠㅠ 혹시 힌트 조금만 주실 수 있을까요??
동적 경로라면 외부 url인가요? 아니면 react-router-dom을 사용해 path에 :slug 이런식으로 slug값을 넣어주시는걸 말씀하시는걸까요~?
후자라면 이 [공식문서](https://reactrouter.com/en/main/routers/create-browser-router#routes) 참고해보세요! 

### Nav 컴포넌트 같이 모든 페이지에 전역적으로 들어가는 컴포넌트에 대해, 특정 페이지에서만 스타일을 바꾸려면 어떻게 해야할지 힌트 주실 수 있을까요?!? (기본 사항 - 폴더 페이지에서 상단 네비게이션 바는 스크롤 시 상단에 고정하지 않고 가려지도록 했나요? 파트)
특정 페이지에서만 스타일을 바꾸고싶다면 path를 prop으로 내려주시거나 location.pathname을 받아와서 분기해주면 되겠죠?

### 컴포넌트 파일들은 css module을 사용하고, page 파일들은 styled component를 사용하려는데 이렇게 css를 섞어써도 괜찮을까요? page 파일은 css 코드나 html 코드가 많지 않아 굳이 css 파일을 분리하기보단 인라인 스타일로 관리하는 게 더 좋지 않을까 싶어 그렇습니다!!
음 아뇨, 섞어쓰는건 조금 어색해보일것같아요 ㅎㅎ css module을 사용하셨다면 굳이 css-in-js없이 기존의 css가 가지고있던 고질적 문제를  해결해보려고 노력해보시는걸 추천드리겠습니다!

### SearchBar.module.css 파일 코드를 정리하는데, input:focus 코드를 nesting 하려고 부모 스타일 안에 밀어넣으면 작동을 안합니다. 왜 그런 건가요???
생략된 자손 결합자를 제대로 써서 `&.input:focus` 로 시도해보실래요?

2023-11-01 08:49 UTC, Hongjw030 commented on src/components/Card/Card.js
> +import noImage from "../../assets/no-img-card.svg";
svg 최적화는 몰랐던 부분인데 알려주셔서 감사합니다!!!! 
그런데 혹시 컴포넌트로 바꿔본다는 게 어떤 뜻일까요??!

2023-11-02 00:40 UTC, addiescode-sj commented
조금 오래걸리는것같으니, 일단 머지할게요!

2023-11-02 00:40 UTC, merged