[강현지] Week8
codeit-bootcamp-frontend/1-Weekly-Mission pull request #374
Opened 2023-10-29 14:47 UTC by kanglocal

## 요구사항

### 기본

- [x] 폴더 페이지의 url path는 ‘/folder’가 되도록 설정해 주세요.
- [x] 폴더 페이지에서 상단 네비게이션 바는 스크롤 시 상단에 고정하지 않고, 가려지도록 해주세요.
- [x] 폴더 목록에 필요한 데이터는 “/api/users/1/folders”를 활용해 주세요.
- [x] Mobile에서 “폴더 추가" 버튼은 최하단에서 101px 떨어져있는 Floating Action Button으로 만들어 주세요.
- [x] 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/users/1”을 활용해 주세요.
- [ ] “전체” 폴더에 필요한 링크들 데이터는 “/api/users/1/links”를 활용하고, 이외의 폴더에 필요한 링크들 데이터는 “/api/users/1/links?folderId={해당 폴더 ID}”를 활용해 주세요.
- [ ] 폴더 버튼을 클릭하면 폴더에 해당하는 링크들로 카드를 구성해 주세요. 폴더에 링크 데이터가 없을 때는 저장된 링크가 없다는 UI를 보여주세요.
- [ ] “전체” 폴더를 선택한 경우 “공유”, “이름 변경”, “삭제” 버튼들이 보이지 않지만, 다른 폴더를 선택한 경우에는 버튼들이 보이도록 해주세요.

## 주요 변경사항

- component 분리
- css파일 분리
- Folder페이지 생성

## 스크린샷

![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/96380950/1b88bfce-df52-4c7c-b81a-57f3a2900853)
![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/96380950/f9bf60c9-0855-4e53-84ea-68e3c020384f)

## 멘토에게

- 컴포넌트와 css파일을 분리시키는데에 시간을 다 써서 완성을 못했습니다, 죄송합니다. 폴더구성을 중점으로 봐주시면 감사하겠습니다..!

2023-10-31 00:12 UTC, addiescode-sj requested changes
현지님~ 리액트를 잘 사용해주고계시네요! 물론 미완성이라고 하셨지만 컴포넌트를 적절히 분리하고, hook도 쓰임새에 맞게 활용해주신것 같아요. 조금만 디테일에 신경써주면 멋진 프로젝트가 될 것 같아요!
다만, setState할때의 setter function을 부모에서 자식으로 내려주고 자식에서 state 업데이트를 하는건 안티패턴인데요, state 업데이트하는 로직을 함수로 감싸서 부모에서 내려주고 자식에서 실행시키게끔 바꿔주세요 :) 미디어쿼리 교차 지점도 없애주시고요!

이 두가지에 대한 수정이 우선적으로 반영될 필요가 있어보입니다!

이번주도 수고하셨습니다~~! 👍

2023-10-31 00:12 UTC, addiescode-sj commented on src/pages/shared/SharedPage.js
hook들 적절하게 잘 이용해주시는것같아요! 굳굳

2023-10-31 05:01 UTC, kanglocal commented on .prettierrc.json
> +  "importOrder": [
ㅜㅜㅜ 왜인지 바뀌지않더라구요.... 

`
import Card from './Card';
import React from 'react';
`

테스트해본것은 위와 같이 순서 바꾸어서 저장해본 것 이었는데, 바뀌지않습니다ㅠㅠ

2023-10-31 05:04 UTC, kanglocal commented on src/components/App.js
> +      <div>
앗 아니요! 필요없는부분이었네요, 삭제하겠습니다!

2023-10-31 05:12 UTC, kanglocal commented on src/components/card/Card.js
> +            src={image_source ?? imageSource ?? noImage}
넵 맞습니다! 
![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/96380950/ddcd6ce2-ac28-47b9-9d6e-6a99d51137bd)
![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/96380950/cd0e9213-9101-4ce5-9b4c-8500b1306427)
위 두 결과 데이터를 한 페이지에 넣다보니, 받고있는 데이터의 key가 달라서(하나는 image_source, 하나는 imageSource 로 달라서) 두 개 다 집어넣게되었습니다.

2023-10-31 20:10 UTC, kanglocal commented on src/components/footer/FooterStyle.css
> +@media (max-width: 768px){
이 부분은 width가 768보다 작은 경우, 위에있는 미디어쿼리만 적용하고, 
572보다 작아지는 경우, 위와 아래의 미디어쿼리 모두를 적용하기위해 작성한것이어서 
교차지점을 없애면 원하는데로 스타일이 나오지않습니다ㅜㅜ
![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/96380950/7825feab-c15c-4408-a5c9-dcec8584c484)

2023-10-31 21:25 UTC, kanglocal commented on src/components/card/Card.js
> +  data: { created_at, createdAt, description, image_source, imageSource, url },
모두 data 바로 아래에 있는 아이들이어서 optional chaining을 어떻게 사용해야할지 잘 모르겠습니다ㅜㅜㅜ

넘어오는 데이터 예시)
![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/96380950/c7c4ccbb-9089-4b4e-ba87-9110efc09fee)

2023-11-01 00:35 UTC, kanglocal commented on src/constants/globalImages.js
>  import SearchIcon from '../assets/icon_search.svg';
멘토님, 혹시 globalImages.js가 constants(상수)폴더에 들어있는데 이렇게 두는것보다 asset폴더에 같이 두는 것이 좋다는 말씀이실까요??

2023-11-01 01:21 UTC, addiescode-sj commented on src/constants/globalImages.js
>  import SearchIcon from '../assets/icon_search.svg';
@kanglocal 

아하 asset폴더에 이미지,로고,svg등 외부 static파일들이 모아져있는게 맞군요! 그러면 파일 위치는 상관없습니다 ㅎㅎ

다만 이 이미지들이 항상 한꺼번에 동시에 쓰이는게 아니라면 이런 이미지맵 경로들을 import해서 모아놓고 다시 export하고 -> 필요한 부분에서 또 import해오는건 불필요한것같긴해요..!

받아올때 import 구문을 최대한 한줄에 줄여서 쓰고싶어하시는 의도는 알겠지만, 모듈은 필요할때만 import하시는게 번들링 효율을 위해서는 좋답니다. 웹팩같은 모듈 번들러는 모듈 그래프를 평평하게(flat하게) 만들고 병합하기때문에, 처리 속도가 빨라지거나 느려지는걸 사용자(개발자) 입장에서는 캐치하기어렵지만 실제로 모듈 그래프의 크기가 처리속도에 영향을 끼칠수있기때문이예요.

조금 딥하긴 하지만 [이 글](https://github.com/yeonjuan/dev-blog/blob/master/JavaScript/speeding-up-the-javascript-ecosystem-the-barrel-file-debacle.md?utm_source=substack&utm_medium=email) 읽어보시면 이유를 알수있을거예요 ㅎㅎ

2023-11-01 01:46 UTC, addiescode-sj commented on src/components/card/Card.js
> +  data: { created_at, createdAt, description, image_source, imageSource, url },
@kanglocal 

아하! ㅎㅎ 
Card 컴포넌트 props는 `function Card({ data }) {}`
이렇게 깔끔하게 받아주시고, `data?.created_at` 이런식으로 optional chaining을 하는게 좋겠다는 의미였습니다 ㅎㅎ

2023-11-01 01:49 UTC, addiescode-sj commented on .prettierrc.json
> +  "importOrder": [
@kanglocal 

네, 바뀌지 않는 이유가 있습니다 ㅎㅎ
저는 @components등으로 이름을 붙여서 절대경로를 지정해서 쓰고있었거든요 ㅎㅎ
그걸 그대로 쓰시니까 경로가 제대로 안잡혀서그럴거예요.

[이글](https://velog.io/@rimo09/React%EC%97%90%EC%84%9C-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EA%B2%BD%EB%A1%9C-%EA%B9%94%EB%81%94%ED%9E%88-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0) 보시고 절대경로 쓰는걸로 바꿔보세요!

2023-11-01 01:50 UTC, addiescode-sj commented on src/components/footer/FooterStyle.css
> +@media (max-width: 768px){
아하 그렇게 의도된 설계였군요! ㅇㅋ 이해했습니다~~

2023-11-01 09:54 UTC, addiescode-sj approved these changes
현지님 훨씬 코드 깔끔해졌네요 ㅎㅎ 수고하셨어요~!!! 👍

2023-11-01 09:55 UTC, merged