[안희원] Week13
codeit-bootcamp-frontend/1-Weekly-Mission pull request #472
Opened 2023-12-03 07:33 UTC by naya-h2

## 요구사항

### 기본

- [x] ‘/folder’ 페이지를 Next.js 프로젝트에 맞게 변경 및 이전 했나요?
- [ ]  ‘/shared’ 페이지를 Next.js 프로젝트에 맞게 변경 및 이전 했나요?
- [ ] 다른 페이지로 이동이 필요한 곳에 next/link의 Link를 적용했나요?
- [ ] Input 컴포넌트에 값이 없는 경우 회색의 placeholder값을 볼 수 있나요?
- [ ] Input 컴포넌트에 focus in 하면 파랑색 테두리를 볼 수 있나요?
- [ ] Input 컴포넌트에 눈 모양 아이콘을 누르면 비밀번호 가리기/보기 기능이 토글 되나요?
- [ ] Input 컴포넌트에 값이 에러케이스일 경우 빨강색 테두리와 에러 메세지를 볼 수 있나요?
- [ ] 컴포넌트에서 focus out 하면 실행할 함수를 설정할 수 있나요?

## 주요 변경사항

- Button, Modal 컴포넌트를 리팩토링하였습니다.
- 홈페이지(/)를 구현하였습니다.
- 페어프로그래밍으로 Input 컴포넌트를 구현하였습니다.

## 스크린샷

![week13](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/103186362/2c14283e-2ebc-4b75-9250-1ad1d8234794)

## 멘토에게

- **Image 관련 warning**이 많이 뜨는데, 관련 코드에서 코멘트로 질문 남기겠습니다!
- 현재 제 페이지에서는 `/folder`에서 url 변화 없이 search 결과를 보여주는 방식입니다. 그런데 강의에서도 그렇고, 여러 다른 사이트들에서 검색을 해보니 /search 페이지를 따로 만들고, 해당 경로에서 search 결과를 보여주는 방식이더라구요. 그래서 /search 페이지를 따로 만드려고 보니 /folder 페이지와 레이아웃이 거의 비슷해서 괜히 불필요하게 컴포넌트를 또 불러오는건가 생각도 들고,, **/search 페이지를 만들 필요가 있을까요?**
- 위에 질문에 이어서, 저는 **검색 query**도 보여주지 않는 상태인데, 보여줄 필요가 있을까요?
- `getSeverSideProps` 한 번 사용해보고 싶었는데 어떤 식으로 해야할지 아직은 감이 안잡혀서 못했네요,,💦
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-03 08:08 UTC, naya-h2 commented on components/common/Card/Card.tsx
> +        <Img src={imageSource || image_source || defaultImg} alt="카드 이미지" width={700} height={700} priority />
이 부분에서 `defaultImg`를 불러오긴 하지만, image가 있을 경우 `defaultImg`를 사용하지 않기 때문에 warning이 뜨는 것 같은데,, 어떤 식으로 바꿔야 없앨 수 있을까요?

![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/103186362/f8e84838-1d1b-43a1-bde8-4812f865412d)

2023-12-03 08:08 UTC, naya-h2 commented on components/common/Input.tsx
페어프로그래밍을 진행한 컴포넌트입니다.

2023-12-03 08:08 UTC, naya-h2 commented on components/common/Input.tsx
> +export default function Input({ passwordMode, errorMessage = '', placeholder, focusOutHandler }: Props) {
focusOutHandler에서 error 관련 검사를 진행하고, 에러 메세지를 return해주는 방식으로 사용하면,
errorMessage Prop은 제거해도 될 것 같네요! 다음주에 수정해보겠습니다 ✅

2023-12-03 08:08 UTC, naya-h2 commented on components/common/Modal/Modal.tsx
기존에는 InputModal.tsx, DeleteModal.tsx 등.. 방식으로 각 모달의 유형마다 컴포넌트를 제작했었는데,
하나의 Modal 컴포넌트를 재사용할 수 있도록 리팩토링하였습니다. 

+어디서 보니까 또 이렇게 컴포넌트 안에서 type으로 나누는게 안티패턴이라고 하네요..........?🥹💦💦 멘토님은 어떻게 생각하시는 지 궁금해요,,ㅜㅜ

2023-12-03 08:08 UTC, naya-h2 commented on components/common/Modal/Modal.tsx
> +  const linkCountData = useGetLinkCount(1);
해당 변수는 type이 add인 경우에만 사용하는데, 조건문 안에서 변수를 선언할 수는 없어서..
근데 이 부분 때문에 **다른 type의 modal을 사용할 때 불필요한 get**을 해와서 고민입니다.

이런 부분이 여러 type을 하나의 컴포넌트에서 처리하는 단점일까요,,

2023-12-03 08:08 UTC, naya-h2 commented on components/folder/AddFolderBtn.tsx
> +        )}
이 부분에서 해당 warning이 뜨면서, 현재 이미지를 조건에 맞게 잘 불러오지 못하는 상태입니다.
(pc, tablet 사이즈일 때도 모바일 버튼 이미지를 불러옵니다...)
잘못 import해오지도 않았는데,, 도대체 뭐가 문제일까요..ㅠㅠ?

![image](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/103186362/4934cdfb-213c-4ef1-a3fa-59d6625272bd)

2023-12-03 08:08 UTC, naya-h2 commented on components/folder/AddLinkBar.tsx
> +      </Bottom>
이 부분을 하나의 LinkBar 컴포넌트만 사용하는 방식으로 고쳐보려고 했는데... 도저히 모르겠습니다 🥹💦💦
일단은 state를 이용해서 두 컴포넌트의 input value를 연동되도록 한 상태입니다.

2023-12-03 08:08 UTC, naya-h2 commented on hooks/useGetData.ts
> +function useGetData<T>(path: string, query: string = ''): T | null {
제네릭을 사용해 타입을 좁히는 방법으로 수정했습니다.

2023-12-03 08:08 UTC, naya-h2 commented on lib/utils/filterLink.ts
> +export function filterLink(links: LinkType[] | SampleLinkType[], search: boolean, keyword: string): any {
return type에 any를 설정한 이유는,
제 의도대로라면 `LinkType[] | SampleLinkType[]` 이여야 하지만,
저는 sample 데이터를 그냥 data와 같은 구조로 가공을 하지 않았기 때문에, 둘의 타입이 다른 상황입니다.
그런데 filter 메소드를 사용하면서 return 타입이 `(LinkType | SampleLinkType)[]` 으로 바뀌어 버려서 일단 any로 설정해 둔 상태입니다..!

각 유저의 folder 데이터를 받아오는 것으로 shared 페이지를 업데이트하게 되면,, sample 데이터를 사용하지 않을것이라고 생각해 일단 고치진 않았는데 추후에 수정해보도록 하겠습니다!

2023-12-03 08:08 UTC, naya-h2 commented on lib/utils/shareLink.ts
> +}
해당 핸들러는 share 타입의 Modal에서만 사용하기 때문에, Modal 컴포넌트에서 선언되는게 별로 좋지 않은 것 같아서 util로 분리하였습니다.

2023-12-03 08:08 UTC, naya-h2 commented on next.config.js
> +      },
현재 저희 페이지는 어떤 도메인을 가진 이미지가 들어올 지 모르는 상황인데, 이렇게 하나하나 다 작성을 하게 되면 언젠가는 이미지 관련 에러가 발생할 수도 있을 것 같다는 생각이 들었습니다..
(현재 저도 user1의 데이터에서 에러를 보고 해당 도메인들을 추가해놓은 상태입니다,... 과연 user`n`이 들어왔을 때 에러가 안난다고 장담할 수 있을까요..ㅠㅠ??)

이렇게 하나하나 추가해주는 방법이 맞는건가요? 아니면 다른 좋은 방법이 있나요?!

2023-12-04 03:55 UTC, Nico1eKim reviewed
이 똑순이를 어떡하면 좋아.... 진짜 넌 크게 될거야 아니원 나도 키워조.... 🫶🏻

2023-12-04 03:55 UTC, Nico1eKim commented on components/common/Button.tsx
> +      {type === 'linkAdd' && <LinkAddBtn>{children}</LinkAddBtn>}
이이이이걸ㄹ 위클리미션에..! 나도... 끌어와야지~~ 근데 리팩 너무 귀찮아서 끝없이 미루는중... 점점 더러워지는 내 코드~

2023-12-04 03:55 UTC, Nico1eKim commented on components/folder/FolderNav.tsx
> +}
우와..! 신기하다..! 역시 똑순이....

2023-12-04 03:55 UTC, Nico1eKim commented on components/home/Contents.tsx
???????? 홈페이지를 만들다니................ 제 signin은 아무것도 아니지만... 당신 홈페이지는.... 언제 이런걸,..... 진심 똑순이 그 잡채네... 나도 빨리 리액트화(?)해서 가져와야겠다.... 흐헝헝ㅇㅇ

2023-12-04 03:55 UTC, Nico1eKim commented on components/home/Main.tsx
이건 진심 배신이에요.

2023-12-04 03:55 UTC, Nico1eKim commented on constants/default.ts
와 여기 코드 진심 기깔난다... 장바구니 줍줍하고싶은데 너무 거대해서 따라하지도 못하겠어

2023-12-04 03:55 UTC, Nico1eKim commented on lib/utils/shareLink.ts
> +      DESC: `${title} 폴더에 담긴 링크가 궁금하다면!! (๑•̀༚•́)ฅ`,
기여어 아니원 기여어....

2023-12-04 03:55 UTC, Nico1eKim commented on pages/_app.tsx
> +        <meta name="description" content="나만의 Link 도서관 | 세상의 모든 정보를 쉽게 저장하고 관리해 보세요" />
메타태그까지 설정하는 이 섬세함..... 본받아야지

2023-12-04 05:02 UTC, Ssong-Q commented on next.config.js
> +      },
아..!! 이렇게 하는 방법이 있군요..! 참고하겠습니당 ㅎㅎ
저는 에러메시지에서 나온 부분 긁어서 햇었는데..!

2023-12-04 05:05 UTC, Ssong-Q commented on hooks/useGetData.ts
> +function useGetData<T>(path: string, query: string = ''): T | null {
주석으로 param과 returns를 위에 적어주시는게 너무 좋은 것 같아요..! 저도 저 방법 줍줍해서 써봐야겠네요 ㅎㅎ

2023-12-04 05:08 UTC, Ssong-Q commented on components/folder/AddFolderBtn.tsx
> +        )}
Image 에러 진짜 그만 보고싶네요 징짜 ㅠ 너무나도 익숙한 화면..ㄷ 
우우~ Next.js 에러 warning 우우~ ㅠㅠ

2023-12-04 05:09 UTC, Ssong-Q commented on components/common/Card/Card.tsx
> +        <Img src={imageSource || image_source || defaultImg} alt="카드 이미지" width={700} height={700} priority />
이건 저도 심심찮게 봤던 warning이라 너무 궁금하네요

2023-12-04 07:17 UTC, naya-h2 commented on hooks/useGetData.ts
> +function useGetData<T>(path: string, query: string = ''): T | null {
@Ssong-Q jsdoc 조아용 강추 👍 👍 👍

2023-12-04 07:19 UTC, naya-h2 commented on components/common/Button.tsx
> +      {type === 'linkAdd' && <LinkAddBtn>{children}</LinkAddBtn>}
@Nico1eKim 진짜 김나은의 버튼 컴포넌트 짱이라구 ~!!~~

2023-12-04 07:21 UTC, naya-h2 commented on constants/default.ts
@Nico1eKim 이미지 import 때문에 쓸데없이 거대해진 것,, 막상 보면 별거업숨.

2023-12-05 00:37 UTC, addiescode-sj requested changes
희원님 수고하셨어요!
next.js랑 타입스크립트 둘다 적용중이신데, 
좋은 시도들도 많이 보이고 코드 작성이나 주석도 꼼꼼하게 쓰셔서 이해하기 수월했던것같아요.
현재 hydration error도 하나보이고, 구조적으로 정리하면 좋을 포인트가 몇개 보여서
request changes 드려보겠습니다.

수요일까지 hydration error 우선적으로 리팩토링해주세요! ㅎㅎ 이번주 너무 수고하셨습니다~~! 👍

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Button.tsx
> +  type: 'add' | 'login' | 'modal' | 'delete' | 'linkAdd';
Button의 type으로 올 수 있는 string 리터럴들을 유니언으로 쓰신 점 아주 칭찬드립니다 👍 
타입을 쓰는것만으로도 Button 컴포넌트의 type variation은 `'add' | 'login' | 'modal' | 'delete' | 'linkAdd'`가 존재할수있다는 의도를 반영할수도있고, 타입스크립트 너무 좋죠? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on constants/dataType.ts
constants 폴더 따로 만들어서 공용으로 쓰이는 상수 관리해주셨네요! 좋은 시도입니다 👍 
다만, 여기있는 dataType.ts 는 상수라기보다는 api response type에 쓰이는 types라서,
해당 디렉토리 안에 있는 다른 파일들과 무관한것같아요. 

이런건 api 폴더에서 api에 관련된 파일들과 같이 위치시켜주는게 어떨까요? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on constants/dataType.ts
> +  profileImageSource: undefined;
요 타입은 좀 특이하네요? ㅎㅎ 서버에서 `profileImageSource` 이 항상 undefined로 오나요?
혹은 값이 오지 않을까요? ㅎㅎ 값이 오지 않는경우가 있는거라면 `profileImageSource?: string`으로 표현해주시는게 더 적절할것같아요! :)

2023-12-05 00:37 UTC, addiescode-sj commented on constants/dataType.ts
> +export interface UserType {
data안에 타입을 넣어주는 반복적인 패턴이 보이네요! 
이런 generic type 하나 만들어두고 여기저기서 쓰면 따로 타입을 만들어줄 필요없이 요긴하게 쓸수있지않을까요? ㅎㅎ 

그리고 이미 타입을 작성하고있는거여서, `UserType`처럼 뒤에 Type 따로 붙여주지않아도 좋습니다! ㅎㅎ

```
export interface User {
  id: number;
  created_at: string;
  name: string;
  image_source: string | null;
  email: string;
  auth_id: string;
  profileImageSource: undefined;
}

export type CommonData<T> = { data: T }
export type UserData = CommonData<User>

const temp: UserData = {data: {id: 1, created_at: '', name: '', image_source: '', email: '', auth_id: '', profileImageSource: undefined}}
```

2023-12-05 00:37 UTC, addiescode-sj commented on constants/dataType.ts
> +export interface FolderListType {
`FolderListType`, `LinkListType` 다 위에있는 `UserType` 처럼 generic 써주면 코드도 줄일 수 있고, 더이상 타입을 따로 만들 필요가 없어지겠죠? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on constants/default.ts
오호 저는 이런 배럴 파일을 따로 만들고, export 하는걸 선호하지않긴해요.
그런데 다 편의성 & 의도가 있어서 쓰는거니까 이 코멘트 내용은 반영 안해주셔도 무관하긴합니다 ㅎㅎ

이미지를 가져올때 import구문이 컴포넌트 코드 작성할때 길어진다고해서 따로 이런 파일을 만들고 한번 더 export -> import하는건 결과적으로 번들링 효율에 좋지않아요.

이미지를 가져올때 import 구문을 최대한 한줄에 줄여서 쓰고싶어하시는 의도는 알겠지만, 모듈은 필요할때만 import하시는게 번들링 효율을 위해서는 좋답니다. 웹팩같은 모듈 번들러는 모듈 그래프를 평평하게(flat하게) 만들고 병합하기때문에, 처리 속도가 빨라지거나 느려지는걸 사용자(개발자) 입장에서는 체감하기어렵지만 실제로 모듈 그래프의 크기가 처리속도에 영향을 끼칠수있기때문이예요.

조금 딥하긴 하지만 [이 글](https://github.com/yeonjuan/dev-blog/blob/master/JavaScript/speeding-up-the-javascript-ecosystem-the-barrel-file-debacle.md?utm_source=substack&utm_medium=email) 읽어보시면 이유를 알수있을거예요 ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on constants/sampleDataType.ts
요런 타입 정의들도 같이 constants 폴더에 있다기보다는,
data response 타입이라면 api 호출에 관련된 파일끼리 모아주시고
아니라면 따로 types 폴더를 만들어서 쓰시는걸 추천드릴게요! ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on constants/sampleDataType.ts
> +  title: string | null;
혹시 값이 없음을 명시적으로 표현하기위해서 null처리를 해주시는건가요?
아니면 type에 optional flag를 붙여서 undefined일수도 있음을 알려주는게 예외처리하는 코드가 더 깔끔해질까요? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on docs/week12/README.md
우와 docs폴더가 주차별로 다 따로 나눠져있었군요! 예뻐요 ✨

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Card/Card.tsx
> +        <Img src={imageSource || image_source || defaultImg} alt="카드 이미지" width={700} height={700} priority />
아하 이건 사실 next/image 컴포넌트에서 `priority={true}`로 넘겨줬기때문에 뜨는 워닝인걸로 보여요. 

이 워닝이 보이는 이유는 preload를 하는데, 로드한 이미지가 곧바로 쓰이지않았기때문인데요, 위에 쓰인 `Link` 컴포넌트에서 `rel="preload" as="image"`를 추가해보실래요? 혹시 의도하신게 아니라면 `priority={true}` 를 없애주셔도되고요!

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Card/Card.tsx
> +const font = css`
오 요렇게 css 나눠쓰신거 좋은 시도인데요? 👍

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Card/Card.tsx
> +    ${TextBox} {
스타일드 컴포넌트 활용 잘하시네요! ㅎㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Card/CardList.tsx
> +  const sampleLinks = useGetSampleLinks();
useGetSampleLinks같은 custom hook으로 api 호출하는 관심사를 분리하시고, 내부 내용을 숨기신것 아주 좋은 시도입니다 👍 다만 앞에 use~같은 접두사가 붙은 함수는 리액트에서 hook으로 분리돼요. 그런데 만약 이렇게 열심히 만들어놓은 함수를 CSR이 아니라 SSR이나 SSG 방식으로 프리렌더링할때 쓰고싶다면, 조금 문제가 될수있겠죠? 

리액트는 hydration단계에서 연결되니까요. 이 부분 next.js app에서는 구조상 리팩토링이 필요할수도있겠네요 👍

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Footer.tsx
> +          {SNS_LIST.map((sns) => (
```suggestion
          {SNS_LIST.map(({ url, alt, src }) => (
```
이런식으로 destruction해서 가져오게되면 sns.url과 같이 접근하지 않아도 되겠죠? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Input.tsx
> +export default function Input({ passwordMode, errorMessage = '', placeholder, focusOutHandler }: Props) {
넵 추가적으로 따로 규칙이 있는건 아니지만, 보통 이벤트 핸들러는 이런 형식을 지켜서 네이밍해주는 편이예요 ㅎㅎ
참고해주세요! ㅎㅎ

`handleClickButton` handle + 이벤트 + 이벤트 대상

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Input.tsx
> +    <>
오잉 여기 fragment 빼주셔도되는거아닐까요? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Input.tsx
> +        <InputWrapper onBlur={focusOutHandler} placeholder={placeholder} type={password ? 'password' : ''} className={errorMessage ? 'error' : ''} />
```suggestion
        <InputWrapper onBlur={focusOutHandler} placeholder={placeholder} {...(password && { type: 'password' })}  {...(errorMessage && { className: 'error' })}/>
```

음 이게 더 깔끔한가..? ㅎㅎ 이렇게 넣어주면 실제로 password, errorMessage가 있을때에만 props 를 추가해줄수있어요.
뭐가 더 깔끔해보이는지는 애매하긴한데, 그래도 빈문자열로 넣는것보단 이게 나을것같기도하네요? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Kebab.tsx
> +    setPopup(!popup);
핸들러이름과 같이, `handlePopupOpen`이니까 setPopup setter function에서 업데이트되는 값은 토글된다기보다는 true가 들어가는게 더 의미가 맞겠죠? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Kebab.tsx
> +  const { isOpen, handleModalOpen, handleModalClose } = useModal();
useModal 아주 좋습니다 👍 👍

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Kebab.tsx
> +          {modal === 'add' && <Modal type="add" title="폴더에 추가" data={url} button="추가하기" onClickClose={() => handleModalClose()} />}
onClickClose props의 handleModalClose는 parameter를 넣어서 실행해주는 부분이 없는데, 이렇게 바꿔보실래요? ㅎㅎ
```suggestion
          {modal === 'add' && <Modal type="add" title="폴더에 추가" data={url} button="추가하기" onClickClose={handleModalClose}
```

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Modal/Modal.tsx
ㅎㅎㅎ 저는 리액트 컴포넌트는 상속보다는 조합! 에 특화되어있다고 생각해요.
type에 의해 분기되어서 문제가 있다기보다는, 우선 이 컴포넌트에서 ui가 각자 어떤 역할을 하는지 명확하게 전달되지않는게 이슈가 조금 있을 수 있다고 생각하는데, 이 기회에 [합성 컴포넌트 패턴](https://fe-developers.kakaoent.com/2022/220731-composition-component/) 써보시는게 어떨까요? ㅎㅎ 훨씬 구조가 한눈에 들어오고, 조합해서 사용할수있으니 재사용성도 증대될거예요 :) 리팩토링 주제로 추천드려볼게요!

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Modal/Modal.tsx
> +  const linkCountData = useGetLinkCount(1);
우선 바로 위에서 코멘트드렸던 합성 컴포넌트 패턴 써보시고요! ㅎㅎ

해당 변수는 type이 add인 경우에만 사용하는데 -> 우선 리액트에서는 use 접두사가 붙은 함수는 모두 hooks로 인지해요. 

따라서, type이 add인 경우에만 사용하려면 따로 조건식을 상수화해서 해당 조건일 경우 어떤 일을 수행한다가 분명해지면 좋은데, 커스텀 훅 내부로 감춰버려서 이 파일에서 확인할수없는게 조금 아쉽긴하네요. 이 부분도 리팩토링해볼까요?

커스텀 훅을 사용하지않고도 똑같은 일을 할수있게 바꿔주세요! ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/folder/AddFolderBtn.tsx
> +        )}
말그대로 hydration error입니다. 

Next.js에서 SSR -> CSR 되면서 도중에 result가 달라졌기때문에 생긴 오류인데요, `const innerWidth = useGetWindowWidth();`은 react hooks니까 hydration 단계에서만 실행되겠죠? 그리고 해당 hook내부에서 window를 참조할때도 hydration이 마쳐진걸 보장받은 시점에서 실행될거고요. 

([학습 QnA 답변](https://discord.com/channels/1141253983000866866/1141578375643807746/1179684861016018955) 참고: Next.js에서 제공하는 Server Side Rendering(SSR)에서는 window, document 같은 브라우저 전역 객체를 사용할 수 없다. window 객체는 client-side에만 존재한다. => 따라서, 페이지가 client에 로드되고 window 객체가 정의될 때까지 window에 접근할 수 없다)


그런데 여기 쓰인 이미지들은 이 innerWidth에 의존하고있네요? ㅎㅎ 이걸 해결할수있는 방법은 innerWidth로 값 업데이트하는것 그리고 button url을 결정해주는것 모두 CSR할때 해결할수있도록 useEffect안으로 넣어주면 해결되겠죠? ㅎㅎ

```tsx
 const [innerWidth, setInnerWidth] = useState(0);
  const [buttonUrl, setButtonUrl] = useState("");

  useEffect(() => {
    if (typeof window === "undefined") return;

    function resizeListener(): void {
      setInnerWidth(window.innerWidth);
    }
    window.addEventListener("resize", resizeListener);
  }, []);

  useEffect(() => {
    if (!innerWidth) return;
    if (innerWidth < 768) {
      setButtonUrl(addMobileButton);
    } else {
      setButtonUrl(addButton);
    }
  }, [innerWidth]);
```

물론 저는 이 방법이 그렇게 썩 마음에 들지는 않습니다..! ㅋㅋㅋ 왜냐하면 window.innerWidth에 의해 알맞은 이미지를 써야할텐데, 결국 hydration 되기전(프리렌더링 시점)까지는 올바른 이미지를 쓸 수 없을테니까요. 

그래도 이런 에러가 왜 나는지 이해하셨으니까, 이 구조적 문제를 최적화해주려면 어떤 일을 해야할지 한번 고민해보시는걸 추천드릴게요 ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/common/Profile.tsx
> +  const innerWidth = useGetWindowWidth();
앗 여기서도 비슷한 문제가...? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/folder/AddFolderBtn.tsx
> +const upDown = keyframes`
조금 더 부드러운 트랜지션을 위해서 opacity도 같이 줘볼까요? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/folder/AddFolderBtn.tsx
> +    ${({ $visibleFooter }) => ($visibleFooter ? yesFooter : noFooter)};
ㅋㅋㅋ귀엽네요 yes no footer 네이밍이 참신하지만, 조금 바꿀 필요가 있어보여요! ㅎㅎ
```suggestion
    ${({ $isVisible }) => ($isVisible ? goDownFooter : goDownFurtherFooter)};
```

2023-12-05 00:37 UTC, addiescode-sj commented on components/folder/AddLinkBar.tsx
> +      </Bottom>
IntersectionObserver 이용해서 visible이라는 값을 true/ false로 잘 업데이트시켜주시고요! (state update) 해당 값이 바뀜에 따라서 현재 styled components 쓰시니까 해당 state를 props로 넘겨서 LinkBar의 css 스타일링이 바뀌어질수있게끔 만들어주면되겠죠? ㅎㅎ 한번 해보시고 어려우시면 dm주세요~

2023-12-05 00:37 UTC, addiescode-sj commented on components/folder/FolderNav.tsx
> +        <FolderNavItem style={folder.id === selectedFolderId ? selectFolderStyle : {}} key={folder.id} folder={folder} onChangeFolder={onChangeFolder} />
여기서도 위에서 코멘트드린것처럼 `folder.id === selectedFolderId` 가 true일때만 props넘길수있게 바꿔주거나, `folder.id === selectedFolderId` 자체를 props로 넘겨서 해당 props 값이 true일때만 스타일링될수있게 바꿔주시는게 깔끔할것같네요 ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on components/folder/FolderTitle.tsx
> +  const title = findFolderTitle(folders, selectedFolderId);
이런 시도 너무 좋네요 👍 👍

2023-12-05 00:37 UTC, addiescode-sj commented on components/folder/LinkBar.tsx
> +    </>
`onClickClose={handleModalClose}`

2023-12-05 00:37 UTC, addiescode-sj commented on hooks/useGetData.ts
> +function useGetData<T>(path: string, query: string = ''): T | null {
@Ssong-Q js doc이랍니다 👍

2023-12-05 00:37 UTC, addiescode-sj commented on hooks/useGetFolders.ts
> +function useGetFolders(userId: number): FolderType[] {
커스텀 훅이.. 아주 많군요? ㅋㅋㅋㅋㅋ
plain react app을 쓸때는 이렇게 api 호출 로직을 커스텀 훅으로 분리해주는게 유지보수에 용이하죠 👍 

다만 next app 쓰실땐 hydration 이슈때문에 이런 hooks들을 CSR 시점에서만 쓸수있다는거 하나 명심해주세요! ㅎㅎ 만약 개발자 입장에서 프리렌더링 방법을 고르고싶다면 hooks 바깥으로 이런 로직들을 꺼내줘야겠죠? ㅎㅎ

2023-12-05 00:37 UTC, addiescode-sj commented on next.config.js
> +      },
ㅎㅎㅎ next/image 안쓰고 직접 이미지 최적화 하시는것도 좋은 방법입니다 (소근소근)

2023-12-05 04:21 UTC, addiescode-sj commented
## 멘토의 답변

### 현재 제 페이지에서는 /folder에서 url 변화 없이 search 결과를 보여주는 방식입니다. 그런데 강의에서도 그렇고, 여러 다른 사이트들에서 검색을 해보니 /search 페이지를 따로 만들고, 해당 경로에서 search 결과를 보여주는 방식이더라구요. 그래서 /search 페이지를 따로 만드려고 보니 /folder 페이지와 레이아웃이 거의 비슷해서 괜히 불필요하게 컴포넌트를 또 불러오는건가 생각도 들고,, /search 페이지를 만들 필요가 있을까요?

단지 개별 라우트를 쓰기위해서 불필요한 라우트를 하나 더 만드시는건 추천드리지않아요 :) search 페이지를 따로 만들 필요는 전혀 없어보입니다. 현재 검색페이지가 따로 존재하는게 아니라 folder페이지에서 검색기능이 포함되어있는 형태로 보여요 :) 

### 위에 질문에 이어서, 저는 검색 query도 보여주지 않는 상태인데, 보여줄 필요가 있을까요?

쿼리 파라미터 쓰면, 검색 결과에 대한 페이지에 접근하고싶을때 바로 접근이 가능해지겠죠?
있으면 next.js에서 라우팅 관련해서 어떻게 동작하나 연습도 해보실겸 좋을것같은데, 위클리미션 내용이 아니니까 필수는 아닙니다 :)

### lib 폴더에는 정확히 어떤 파일들을 넣는건가요,,?! 전 현재 lib/utils 구조로 넣어놨는데, 혹시 lib == utils 이런 느낌인가용??
폴더명은 정해진 정답이 없으므로 컨벤션을 참고만 하시면 됩니다 ㅎㅎ
하지만 디렉토리 구조를 생각하실땐 명확한 기준이 있고 이 기준을 규칙으로 만들어서 폴더나 파일을 만들때, 관련 코드를 작성할때 지켜주시는게 좋습니다. 그리고 폴더 구조가 깊게 설계되어있으면 파일을 찾기가 어렵고 중간에 수정하기도 어려운 문제가 있어서 이 문제점을 미리 해소하시는게 좋아요. 저는 utils는 보통 유틸함수들을 정리해서 모아놓는 용도로 사용하고 lib폴더는 static한 파일들을 모아놓는 편입니다 :) 

### 폴더를 깔끔하게 관리하고 싶은데, src 폴더가 없어져서 그런지... 지금 너무 폴더가 많고 지저분해 보이는 느낌이네요,,ㅠㅠ 깔끔하게 관리할 방법이 있을까요?

next.js에서는 페이지 단위로 컴포넌트를 담아주는 폴더를 분리할수있는데요!
페이지를 구성하기위해 필요한 entry가 되는 컴포넌트들은 해당 폴더 하위에 두시고,
나머지 프로젝트를 구성하는 데 필요한 관련 파일들은 분리하시는걸 더 추천드리긴해요.
예를 들어, 공용 컴포넌트들 모아놓고싶다면 components폴더를 pages폴더 하위에 두지않고 외부 폴더로 분리하는식으로 진행해주시는게 좋습니다 :)

2023-12-05 04:35 UTC, naya-h2 commented on components/common/Modal/Modal.tsx
> +  const linkCountData = useGetLinkCount(1);
@addiescode-sj 음,, 저 함수 자체가 데이터를 불러오고, 그 데이터에서 사용할 정보를 가공해서 주는 커스텀훅 역할인데,, 커스텀훅 없이 똑같은 일을 할 수 있을까요..?ㅠㅠ 애초에 데이터를 불러오는 부분에서 꼭 커스텀훅이 필요해서요...ㅜㅜ

2023-12-05 04:48 UTC, naya-h2 commented on constants/dataType.ts
> +  profileImageSource: undefined;
@addiescode-sj 이 부분은 제가 sample 데이터와 실제 데이터 구조를 통일하지 않아서 발생한 문제인데요..!

sample 데이터의 userdata의 경우, 프로필 이미지를 `profileImageSource` 프로퍼티로 받아오지만, 실제 userdata의 경우 `image_source` 프로퍼티로 받아옵니다.

그런데, 저는 userdata를 구조분해 하는 과정에서 둘을 구분 없이 
```ts
const { name, ~~ , profileImageSource, image_source } = userdata; 
```
형식으로 사용하기 때문에 typescript로 마이그레이션하는 과정에서 에러가 날 수 밖에 없었고, 위와 같이 그냥 type을 undefined로 지정해서 문제를 해결했어요 ㅠㅠ

흠... 옵셔널로 바꿔보거나 sample 데이터를 빨리 그냥 데이터 형식에 맞게 재가공시키거나.... 현명한 방법을 생각해봐야겠네요ㅠㅠ

2023-12-05 06:20 UTC, addiescode-sj commented on components/folder/AddFolderBtn.tsx
> +        )}
@Ssong-Q

2023-12-05 14:55 UTC, naya-h2 commented on components/common/Card/Card.tsx
> +        <Img src={imageSource || image_source || defaultImg} alt="카드 이미지" width={700} height={700} priority />
- `rel="preload" as="image"` 를 추가했을 때는 해당 warning이 발생하고, 카드에 이미지가 아예 보이지 않는 상황이 됩니다.
<img width="266" alt="image" src="https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/103186362/958d6da7-a0c4-4110-8152-18f9d4e64db8">

- `priority`를 없애면 다음 warning이 발생합니다.
<img width="274" alt="image" src="https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/assets/103186362/6130661e-093d-48ce-b59b-85dbfecb787f">

2023-12-05 17:42 UTC, naya-h2 commented on components/common/Modal/Modal.tsx
> +      {type === 'share' && <ShareModal data={data} folderId={folderId} />}
합성 컴포넌트 패턴을 완전히 적용하려면 Modal의 사용처에서 직접 modal 구조를 조합해서 사용하는 방식 같던데,, 저는 이렇게만 적용해보았습니다..!
멘토님이 추천해 주신 의도에 맞게 했는지는 잘 모르겠네요.. ㅜㅜ

2023-12-05 17:42 UTC, naya-h2 commented on components/folder/AddFolderBtn.tsx
> +  }
`useGetWindowWidth()`를 사용해 발생한 hydration error를 **css에서 반응형으로 처리**하는 방식을 사용해 수정해보았습니다.

따라서 useGetWindowWidth 훅은 아예 사라지게 되었습니다.. ㅎㅎ

2023-12-06 08:27 UTC, addiescode-sj commented on components/common/Modal/Modal.tsx
> +      {type === 'share' && <ShareModal data={data} folderId={folderId} />}
네 쉽게 얘기하면 모달을 구성하는 Header, Body등을 분리해놓고 base가 되는 컴포넌트에 object.assign으로 합성하는 형태인데요! 

즉 <ModalHeader /> 컴포넌트를 만드는것보다 <Modal.Header /> 이런식으로 합성해놓으면 modal을 구성해야하는 ui가 어떤 것들이 있는지 무엇을 조합해서 사용해야하는지 구조를 명확히 설계해줄수있게됩니다. 

이걸 시도해보시고, modal type에 맞는 모달을 렌더하는것은 사실 컴포넌트에서 분기처리된다기보다는 받은 input을 가지고 일정한 output을 리턴하는 함수에 좀 더 어울리죠? 함수에 의해 type에 맞는 모달이 리턴될수있도록 해보실래요? ㅎㅎ

2023-12-06 08:28 UTC, addiescode-sj commented on components/folder/AddFolderBtn.tsx
> +  }
css 미디어 쿼리로 간단히 해결될수있는 요구사항이었다면 너무 잘해주셨네요 👍 ㅋㅋ

2023-12-07 01:10 UTC, addiescode-sj approved these changes

2023-12-07 01:10 UTC, merged

2023-12-08 12:39 UTC, Ssong-Q commented on README.md
README.md 와....
나도 리드미 써봐야겠네요 최고최고