Part1 정진호 week3
codeit-bootcamp-frontend/1-Weekly-Mission pull request #71
Opened 2023-09-20 07:09 UTC by ayden94

## 요구사항

### 기본
- [x] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용했나요?
- [x] [랜딩 페이지] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 Linkbrary 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정했나요?
- [x] [랜딩 페이지] 미리보기에서 제목은 “Linkbrary”, 설명은 “세상의 모든 정보를 쉽게 저장하고 관리해 보세요”로 설정했나요?
- [x] [랜딩 페이지] 주소와 이미지는 자유롭게 설정했나요?
- [x] [랜딩 페이지] Tablet 사이즈에서 화면의 너비가 1199px 이하로 작아질 때 “Linkbrary” 로고와 “로그인” 버튼 사이의 간격은 유지하고 좌우 여백이 줄어드나요?
- [x] [랜딩 페이지] 최소 좌우 여백은 “Linkbrary” 로고의 왼쪽에 여백 32px, “로그인” 버튼 오른쪽 여백 32px을 유지할 수 있도록 “Linkbrary” 로고와 “로그인" 버튼의 간격이 가까워지나요?
- [x] [랜딩 페이지] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용했나요?
- [x] [랜딩 페이지] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차나요? (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [x] [랜딩 페이지] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 간격이 커지나요?
- [x] [로그인, 회원가입 페이지] Tablet 사이즈에서 디자인은 PC사이즈와 동일한가요?
- [x] [로그인, 회원가입 페이지] Mobile 사이즈에서 좌우 여백 32px 제외하고 내부 요소들이 너비를 모두 차지하나요?
- [x] [로그인, 회원가입 페이지] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않나요?

### 심화
- [x] 랜딩 페이지 Mobile 사이즈에서 제품 소개 영역의 순서를 제목, 설명, 이미지 => 제목, 이미지, 설명 순서로 변경했나요?
- [x] 팀원의 위클리 미션 PR에 코드 리뷰를 남겼나요?

## 주요 변경사항

- 전 페이지에 걸쳐서 화면의 넓이에 따라 반응하도록 미디어쿼리 사용
- index.html에 오픈그래프를 이용한 메타데이터 삽입

## 멘토에게

- 같은 컴포넌트(.btn)가 index.html에서는 화면 넓이에 따라 글자 크기와 패딩값이 줄어들고, sign에서는 변하지 않습니다. 그렇다면 좁은 화면에서만 반응하는 컴포넌트 클래스(가령 .btn--media768 과 같은 형태로)를 compo.css에 미디어쿼리로 마련하는 게 좋을까요? 아니면 그냥 지금처럼 index.html에서만 .btn이 변하도록 index.css에 미디어쿼리를 배치하는 게 좋을까요?

2023-09-20 10:16 UTC, jayjnu requested changes

2023-09-20 10:16 UTC, jayjnu commented on asset/styles/index.css
> +    right: 0;
left: 0 또는 right: 0 하나만 주면 됩니다.

2023-09-20 10:16 UTC, jayjnu commented on asset/styles/index.css
> +@media (max-width: 1199px) and (min-width: 768px) {
미디어 쿼리 룰은 range를 정의하지 않고 방향으로만 설정하는 것이 좋습니다.
css 는 cascading 된다는 점을 이용하면 됩니다.

```css
@media (min-width: 320px) {}
@media (min-width: 640px) {}
```

예제: https://codepen.io/jayjnu/pen/XWozwrb

2023-09-20 10:16 UTC, jayjnu commented on asset/styles/sign.css
> +    max-width: 40rem;
body에 max width 같은 크기를 지정하기보다는 body하위에 전체 영역을 감싸는 요소를 추가하는 방식으로 변경하는 것이 좋스빈다.

2023-09-20 10:31 UTC, jayjnu commented on asset/styles/component.css
> +    .btn--width-350 {
모든 버튼이 화면비 350px일때 200px이기는 현실적으로 어렵습니다.

버튼같은경우는 특히 내부 컨텐츠 길이도 달라질 수 있기 때문에 위의 방식보다는 해당 페이지에서 특정 block 엘리먼트에 속한 버튼에 대해 스타일 예외처리를 해주는 것이 좋을듯합니다.

2023-09-20 10:34 UTC, jayjnu commented on asset/styles/index.css
> +        position: absolute;
시안상으로 footer 영역에 position을 줄 이유가 없어보이는데요, flex나 margin등을 이용해서 수정해보시는것은 어떨까요?

2023-09-20 10:35 UTC, jayjnu commented
> 같은 컴포넌트(.btn)가 index.html에서는 화면 넓이에 따라 글자 크기와 패딩값이 줄어들고, sign에서는 변하지 않습니다. 그렇다면 좁은 화면에서만 반응하는 컴포넌트 클래스(가령 .btn--media768 과 같은 형태로)를 compo.css에 미디어쿼리로 마련하는 게 좋을까요? 아니면 그냥 지금처럼 index.html에서만 .btn이 변하도록 index.css에 미디어쿼리를 배치하는 게 좋을까요? (커밋 [1ffd657](https://github.com/codeit-bootcamp-frontend/1-Weekly-Mission/pull/71/commits/1ffd6579b0312a12afc57d4d3e7556ae35fede55) 문제)

리뷰로 남겨드렸습니다.

2023-09-21 05:01 UTC, ayden94 commented on asset/styles/index.css
> +@media (max-width: 1199px) and (min-width: 768px) {
PC: 1200px 이상
Tablet: 768px 이상 ~ 1199px 이하
Mobile: 375px 이상 ~ 767px 이하
375px 미만 사이즈의 디자인은 고려하지 않습니다

@media (min-width: 375px) {}
@media (min-width: 768px) {}

제 경우에는 이렇게 하면 되는 걸까요?

2023-09-21 05:03 UTC, ayden94 commented
심화 과제도 제가 해낸 거 같습니다

2023-09-21 15:14 UTC, ayden94 commented
리뷰 주신 부분은 모두 수정하..진 않았고, 딱 하나 body에 max width 주는 내용은 변경을 하기는 했지만 기조 자체는 그대로 유지되었습니다. max w 없이 어떻게 해야할지 감이 많이 안 옵니다.

2023-09-22 14:24 UTC, ayden94 commented
생각해보니까 footer에 position 주는 것도 문제네요. 이것도 grid로 해결하지 않을까 합니다

2023-09-24 12:05 UTC, jayjnu commented on signin.html
> +                <form class="form">
한 페이지에 하나의 form만 있을것이라고 단정할 수 없으므로 더 구체적인 이름이 필요합니다.

2023-09-24 12:05 UTC, jayjnu commented on signin.html
> +                <p class="footer__title">소셜 로그인</p>
title로 쓸 수 있는 태그는 h 계열이나 strong 이 좋을것같습니다. 
h와 strong 태그는 스크린리더에서 강조해서 읽어줍니다.

2023-09-24 12:06 UTC, merged